import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.testimonials': 'Testimonials',
    'nav.faqs': 'FAQs',
    'nav.contact': 'Contact',
    'nav.book': 'Book Appointment',
    
    // Hero Section
    'hero.badge': 'Trusted Professional Services',
    'hero.title': 'New Jersey\'s Most Trusted',
    'hero.title.highlight': 'Mobile Notary',
    'hero.title.end': '& Signing Services',
    'hero.description': 'Licensed, bonded, and insured notary serving Edison, Woodbridge, and surrounding areas. Same-day appointments, bilingual service, and 24/7 availability for your convenience.',
    'hero.feature1': 'NJ Licensed & $50K Insured',
    'hero.feature2': 'Mobile Service (25-mile radius)',
    'hero.feature3': 'Bilingual Service (English/Spanish)',
    'hero.feature4': 'Same-Day Appointments Available',
    'hero.cta.book': 'Book Your Appointment',
    'hero.cta.phone': '(908) 514-8180',
    'hero.stats.documents': 'Documents Notarized',
    'hero.stats.loans': 'Loan Signings',
    'hero.stats.satisfaction': 'Client Satisfaction',
    'hero.image_alt': 'Professional notary services - official documents and seals',
    'hero.badge.licensed': 'Licensed & Bonded',
    'hero.badge.licensed_desc': 'Professional Service',
    'hero.badge.ron': 'RON Certified',
    'hero.badge.ron_desc': 'Remote Notarization',
    
    // About Section - Mission and Why Choose Us
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To provide reliable, professional, and convenient notary services while maintaining the highest standards of integrity and confidentiality. We strive to make document notarization accessible and stress-free for every client.',
    'about.cta': 'View Our Credentials',
    'about.why_choose.title': 'Why Choose Notary and Signings LLC?',
    'about.why_choose.subtitle': 'Our dedication to professional excellence and client satisfaction sets us apart.',
    'about.why_choose.excellence.title': 'Professional Excellence',
    'about.why_choose.excellence.description': 'Licensed, bonded, and insured with continuous education and training',
    'about.why_choose.convenience.title': 'Convenient Service',
    'about.why_choose.convenience.description': 'Mobile services, flexible scheduling, and remote notarization options',
    'about.why_choose.trust.title': 'Trusted Partnership',
    'about.why_choose.trust.description': 'Confidential, reliable service with a focus on building long-term relationships',
    'about.verify_credentials': 'Verify Notary Credentials',
    'about.verify_signing_agent': 'Verify Signing Agent Credentials',
    
    // Services Section
    'services.badge': 'Our Services',
    'services.title': 'Comprehensive Notary Solutions',
    'services.subtitle': 'Professional services tailored to meet your document authentication and signing needs.',
    'services.mobile.title': 'Mobile Notary',
    'services.mobile.description': 'Convenient on-site notary services at your location.',
    'services.mobile.feature1': 'Travel within 25-mile radius',
    'services.mobile.feature2': 'Same-day appointments available',
    'services.mobile.feature3': 'Multiple documents per visit',
    'services.mobile.feature4': 'Bilingual service (EN/ES)',
    'services.mobile.price': '$75/hour',
    'services.mobile.includes': 'Includes: Travel time, document review, notarization, and certificate completion. Additional documents: $15 each.',
    'services.loan.title': 'Loan Signings',
    'services.loan.description': 'Specialized in real estate loan document signings.',
    'services.loan.feature1': 'NNA certified signing agent',
    'services.loan.feature2': 'Error-free document handling',
    'services.loan.feature3': 'Fast scanback to title company',
    'services.loan.feature4': '24/7 availability',
    'services.loan.price': '$100-$150',
    'services.loan.includes': 'Includes: Full loan package review, signing coordination, document return. After-hours (8PM-8AM): +$25.',
    'services.ron.title': 'Remote Online Notarization',
    'services.ron.description': 'Secure online notarization from anywhere.',
    'services.ron.feature1': 'Secure video platform',
    'services.ron.feature2': 'Digital document signing',
    'services.ron.feature3': 'Identity verification',
    'services.ron.feature4': 'Instant completion',
    'services.ron.price': '$35 per document',
    'services.ron.includes': 'Includes: Video session, identity verification, digital notarization, electronic certificate. Multiple docs: $25 each additional.',
    'services.apostille.title': 'Apostille Services',
    'services.apostille.description': 'Document authentication for international use.',
    'services.apostille.feature1': 'International authentication',
    'services.apostille.feature2': 'Document preparation',
    'services.apostille.feature3': 'Fast processing',
    'services.apostille.feature4': 'Secure handling',
    'services.apostille.price': 'From $50',
    'services.fingerprint.title': 'Fingerprinting Services',
    'services.fingerprint.description': 'Professional fingerprinting for background checks and licensing.',
    'services.fingerprint.feature1': 'Live Scan',
    'services.fingerprint.feature2': 'INK Cards',
    'services.fingerprint.feature3': 'Background Checks',
    'services.fingerprint.feature4': 'License Applications',
     'services.fingerprint.price': 'From $20',
     'services.ipen.title': 'In-Person Electronic Notarization (iPEN)',
     'services.ipen.description': 'Electronic notarization performed in-person using secure digital technology and electronic signatures.',
     'services.ipen.feature1': 'Electronic signatures',
     'services.ipen.feature2': 'Digital notary seal',
     'services.ipen.feature3': 'Secure authentication',
     'services.ipen.feature4': 'Immediate processing',
     'services.ipen.price': '+$40 Extra',
     'services.coming_soon': 'Coming Soon',
     'services.ipen.addon': 'Available with any service',
     'services.tax.individual.title': 'Tax Preparation (Individual)',
    'services.tax.individual.description': 'Professional individual tax preparation services.',
    'services.tax.individual.feature1': 'Individual Returns',
    'services.tax.individual.feature2': 'Deduction Optimization',
    'services.tax.individual.feature3': 'E-Filing',
    'services.tax.individual.feature4': 'Tax Planning',
    'services.tax.business.title': 'Small Business Tax Filing',
    'services.tax.business.description': 'Comprehensive tax services for small businesses.',
    'services.tax.corporate.title': 'Partnership & Corporate Taxes',
    'services.tax.corporate.description': 'Advanced tax preparation for partnerships and corporations.',
    'services.tax.review.title': 'Tax Review and/or Amendment',
    'services.tax.review.description': 'Professional review and amendment of existing tax returns.',
    
    'services.tax.amendment.title': 'Tax Amendment Filing',
    'services.tax.amendment.description': 'File amendments to correct or update previously filed tax returns',
    
    'services.tax.quarterly.title': 'Quarterly Tax Estimates',
    'services.tax.quarterly.description': 'Calculate and file quarterly estimated tax payments for self-employed individuals',
    
    'services.tax.prior_year.title': 'Prior Year Tax Returns',
    'services.tax.prior_year.description': 'Prepare and file tax returns for previous years',
    'services.tax.additional.title': 'Additional Tax Services',
    'services.tax.additional.subtitle': 'Specialized tax preparation services for businesses and complex returns.',
    'services.book_now': 'Book Now',
    'services.learn': 'Learn More',
    'services.popular': 'Most Popular',
    'services.areas.title': 'Service Areas',
    'services.areas.description': 'We proudly serve the following areas with mobile services available:',
    'services.areas.scotch_plains': 'Scotch Plains',
    'services.areas.perth_amboy': 'Perth Amboy',
    'services.areas.new_brunswick': 'New Brunswick',
    'services.areas.piscataway': 'Piscataway',
    'services.areas.plainfield': 'Plainfield',
    'services.areas.south_amboy': 'South Amboy',
    'services.areas.availability': 'Mobile Service Available',
    'services.areas.same_day': 'Same-Day Appointments',
    
    // About Section
    'about.badge': 'Woman-Owned Business',
    'about.title': 'About Notary & Signings LLC',
    'about.description': 'Welcome to Notary and Signings LLC, where professionalism meets convenience. We are a bilingual, woman-owned business committed to delivering fast, secure, and accurate notary public services, loan signings, remote online notarizations (RON), and tax preparation to individuals, small business owners, and real estate professionals.',
    'about.owner.name': 'Arlenny Abreu',
    'about.owner.credentials': 'Certified Notary Public, Loan Signing Agent & Tax Preparer (PTIN: P03346699)',
    'about.owner.bio': 'Founded by Arlenny Abreu, a certified Notary Public, Loan Signing Agent, and registered Tax Preparer, Notary and Signings LLC was built with one goal in mind: to make critical document services more accessible, reliable, and client-focused. We proudly serve clients in both English and Spanish, ensuring clear communication, trust, and confidentiality every step of the way.',
    'about.certification.title': 'Professional Certifications',
    'about.certification.description': 'Licensed, bonded, and insured with all required state certifications for your peace of mind.',
    'about.experience.title': 'Years of Experience',
    'about.experience.description': 'Extensive experience in all types of notarial acts and document authentication services.',
    'about.mobile.title': 'Mobile Service',
    'about.mobile.description': 'Convenient on-site services at your home, office, or any location of your choice.',
     'about.stats.certifications': 'Professional Certifications',
     'about.stats.experience': 'Years Experience',
     'about.stats.documents': 'Documents Processed',
     'about.stats.satisfaction': 'Satisfaction Rate',
     'about.insurance.description': '$50K professional liability insurance for your protection',
     'about.ron.description': 'Remote notarization certified through approved platforms',
     'about.loan_signing.title': 'Loan Signing Agent',
     'about.loan_signing.description': 'NNA certified loan signing agent with extensive real estate experience',
    
    // Testimonials Section
    'testimonials.badge': 'Client Testimonials',
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': 'Real experiences from satisfied clients who trust our professional notary services.',
    'testimonials.stats.professional': 'Professional Service',
    'testimonials.stats.satisfaction': 'Client Satisfaction',
    'testimonials.stats.clients': 'Happy Clients',
    'testimonials.stats.rating': 'Average Rating',
    'testimonials.cta.title': 'Ready to Experience Professional Service?',
    'testimonials.cta.description': 'Join hundreds of satisfied clients who trust us with their important documents.',
    
    // Individual Testimonials
    'testimonials.client1.name': 'Sarah Johnson',
    'testimonials.client1.role': 'Real Estate Agent',
    'testimonials.client1.content': 'Notary and Signings LLC has been our go-to for all loan signings. Their professionalism and attention to detail is outstanding. They make the closing process smooth for our clients.',
    'testimonials.client1.service': 'Loan Signing',
    
    'testimonials.client2.name': 'Michael Chen',
    'testimonials.client2.role': 'Small Business Owner',
    'testimonials.client2.content': 'The mobile notary service saved me so much time. They came to my office within 2 hours and handled all my business documents professionally. Highly recommend!',
    'testimonials.client2.service': 'Mobile Notary',
    
    'testimonials.client3.name': 'Lisa Rodriguez',
    'testimonials.client3.role': 'Working Professional',
    'testimonials.client3.content': 'Remote online notarization was perfect for my situation. The video call was secure and professional, and I received my notarized documents immediately. Great service!',
    'testimonials.client3.service': 'RON Service',
    
    'testimonials.client4.name': 'David Thompson',
    'testimonials.client4.role': 'Retiree',
    'testimonials.client4.content': 'Needed my tax return prepared and documents notarized. They handled everything with care and explained each step. Trustworthy and reliable service.',
    'testimonials.client4.service': 'Tax Preparation',
    
    'testimonials.client5.name': 'Jennifer Park',
    'testimonials.client5.role': 'Healthcare Worker',
    'testimonials.client5.content': 'Fast fingerprinting service for my license renewal. Professional setup and quick turnaround. They made the process easy and stress-free.',
    'testimonials.client5.service': 'Fingerprinting',
    
    'testimonials.client6.name': 'Robert Williams',
    'testimonials.client6.role': 'International Student',
    'testimonials.client6.content': 'Needed apostille services for my documents to be used abroad. They handled the entire process and kept me updated throughout. Excellent service!',
    'testimonials.client6.service': 'Apostille',
    
    // FAQ Page
    'faqs.badge': 'Frequently Asked Questions',
    'faqs.title': 'How Can We Help You?',
    'faqs.subtitle': 'Find answers to the most common questions about our notary services, pricing, and processes.',
    'faqs.contact.title': 'Still Have Questions?',
    'faqs.contact.description': 'If you can\'t find the answer you\'re looking for, don\'t hesitate to reach out to us directly. We\'re here to help!',
    
    // FAQ Categories
    'faqs.general.title': 'General Questions',
    'faqs.general.q1.question': 'What is a notary public and what do they do?',
    'faqs.general.q1.answer': 'A notary public is a state-appointed official who serves as an impartial witness to the signing of important documents. We verify the identity of signers, ensure they understand what they\'re signing, and confirm they\'re signing willingly without coercion.',
    'faqs.general.q2.question': 'What documents do I need to bring for notarization?',
    'faqs.general.q2.answer': 'You\'ll need:\n• A valid government-issued photo ID (driver\'s license, passport, or state ID)\n• The unsigned document(s) to be notarized\n• Any additional documentation specified by the document requirements',
    'faqs.general.q3.question': 'Are you licensed and insured?',
    'faqs.general.q3.answer': 'Yes, we are fully licensed notaries public in the state of New Jersey, bonded, and carry $50,000 in professional liability insurance for your protection and peace of mind.',
    'faqs.general.q4.question': 'What are your business hours?',
    'faqs.general.q4.answer': 'We operate Monday through Sunday, 8AM to 8PM, by appointment only. We offer flexible scheduling to accommodate your busy schedule, including evening and weekend appointments.',
    
    'faqs.mobile.title': 'Mobile Notary Services',
    'faqs.mobile.q1.question': 'Do you travel to my location?',
    'faqs.mobile.q1.answer': 'Yes! We provide mobile notary services within 25 miles of Edison, NJ. We\'ll come to your home, office, hospital, or any convenient location for an additional travel fee.',
    'faqs.mobile.q2.question': 'How much does mobile service cost?',
    'faqs.mobile.q2.answer': 'Mobile notary service is $75 for 1 hour, which includes travel time and notarization of your documents. Additional time is billed in 15-minute increments.',
    'faqs.mobile.q3.question': 'How quickly can you come to me?',
    'faqs.mobile.q3.answer': 'We typically can schedule same-day appointments with 2-4 hours notice. For urgent requests, please call us directly at (908) 514-8180.',
    
    'faqs.ron.title': 'Remote Online Notarization (RON)',
    'faqs.ron.q1.question': 'What is Remote Online Notarization?',
    'faqs.ron.q1.answer': 'RON allows you to get documents notarized online through a secure video conference. You can be anywhere in the world while we verify your identity digitally and witness your electronic signature.',
    'faqs.ron.q2.question': 'What do I need for RON?',
    'faqs.ron.q2.answer': 'You\'ll need:\n• A computer, tablet, or smartphone with camera and microphone\n• Stable internet connection\n• Valid government-issued photo ID\n• The document in PDF format (we can help convert if needed)',
    'faqs.ron.q3.question': 'Is RON legally valid?',
    'faqs.ron.q3.answer': 'Yes, RON is legally valid and recognized in New Jersey and many other states. The electronically notarized document has the same legal weight as a traditional paper notarization.',
    
    'faqs.loan.title': 'Loan Signing Services',
    'faqs.loan.q1.question': 'What is a loan signing agent?',
    'faqs.loan.q1.answer': 'A loan signing agent is a specially trained notary who handles the signing of real estate loan documents. We ensure all documents are signed correctly and returned to the title company or lender promptly.',
    'faqs.loan.q2.question': 'How long does a loan signing take?',
    'faqs.loan.q2.answer': 'Most loan signings take 1 hour to complete. We allow sufficient time to review documents, answer questions, and ensure everything is signed properly.',
    'faqs.loan.q3.question': 'Do you work with all title companies and lenders?',
    'faqs.loan.q3.answer': 'Yes, we work with title companies, lenders, and signing services throughout New Jersey. We\'re approved by major title companies and maintain the highest standards of professionalism.',
    
    'faqs.pricing.title': 'Pricing & Payment',
    'faqs.pricing.q1.question': 'What forms of payment do you accept?',
    'faqs.pricing.q1.answer': 'We accept cash, check, Venmo, Zelle, and all major credit cards. Payment is due at the time of service.',
    'faqs.pricing.q2.question': 'Are there any additional fees?',
    'faqs.pricing.q2.answer': 'Our pricing is transparent. Mobile service includes travel within 25 miles. For locations beyond 25 miles, there\'s an additional mileage fee. Rush service (less than 2 hours notice) may include an additional fee.',
    'faqs.pricing.q3.question': 'Do you offer discounts for multiple documents?',
    'faqs.pricing.q3.answer': 'Yes, we offer competitive pricing for multiple documents during the same appointment. Contact us for a custom quote for large document packages.',
    
    // Contact Section
    'contact.badge': 'Contact Us',
    'contact.title': 'Ready to Get Started?',
    'contact.subtitle': 'Contact us today to schedule your notary appointment or get answers to your questions.',
     'contact.info.location': 'Our Location',
     'contact.info.location.address': '180 Talmadge Road, Unit 1380, Edison, NJ 08817',
     'contact.info.location.description': 'Mobile services within 25 miles',
     'contact.info.phone': 'Phone Number',
     'contact.info.phone.description': 'Call us for immediate assistance',
     'contact.info.email': 'Email Address',
     'contact.info.email.description': 'Send us your questions anytime',
    'contact.info.hours': 'Business Hours',
    'contact.info.hours.schedule': 'Mon-Sun: 8AM-8PM',
    'contact.info.hours.description': 'Monday through Sunday availability',
     'contact.form.title': 'Send Us a Message',
     'contact.form.first_name': 'First Name',
     'contact.form.last_name': 'Last Name',
     'contact.form.name': 'Full Name',
     'contact.form.preferred_date': 'Preferred Date',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.service': 'Service Needed',
    'contact.form.service.mobile': 'Mobile Notary',
    'contact.form.service.loan': 'Loan Signing',
    'contact.form.service.ron': 'Remote Notarization',
    'contact.form.service.apostille': 'Apostille Service',
    'contact.form.service.other': 'Other Services',
    'contact.form.timing': 'Preferred Timing',
    'contact.form.timing.morning': 'Morning (8AM-12PM)',
    'contact.form.timing.afternoon': 'Afternoon (12PM-5PM)',
    'contact.form.timing.evening': 'Evening (5PM-8PM)',
    'contact.form.timing.flexible': 'Flexible Timing',
     'contact.form.message': 'Message',
     'contact.form.message_placeholder': 'Please provide details about your notary needs, number of documents, location preferences, or any special requirements...',
    'contact.form.submit': 'Send Message',
    'contact.form.response': "We'll respond within 2 hours during business hours.",
    'contact.hours.monday': 'Monday - Friday',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.appointment': 'By appointment only',
    'contact.hours.appointment_only': 'By Appointment Only',
    'contact.emergency.title': 'Professional Services',
    'contact.emergency.description': 'Licensed, bonded, and insured notary services with flexible scheduling to meet your needs.',
    
    // Footer
    'footer.company': 'Notary & Signings LLC',
    'footer.description': 'Professional notary services you can trust. Licensed, bonded, and insured for your peace of mind. Serving the community with integrity and excellence.',
    'footer.quick_links': 'Quick Links',
     'footer.services': 'Our Services',
     'footer.services.fingerprinting': 'Fingerprinting Services (Coming Soon)',
     'footer.services.tax_preparation': 'Tax Preparation',
    'footer.credentials': 'Professional Credentials',
    'footer.licensed': 'Licensed Notary',
    'footer.licensed_desc': 'State Certified',
    'footer.bonded': 'Bonded & Insured',
    'footer.bonded_desc': '$100K Coverage',
    'footer.ron_certified': 'RON Certified',
    'footer.ron_desc': 'Remote Notarization',
    'footer.verify_notary': 'Verify Notary Credentials',
    'footer.verify_signing': 'Verify Signing Agent Credentials',
    'footer.professional_services': 'Professional Services',
    'footer.professional_desc': 'Licensed, bonded, and insured notary services with flexible scheduling.',
    'footer.schedule': 'Schedule Appointment',
    'footer.copyright': '© 2025 Notary and Signings. All rights reserved.',
    'footer.business_hours': 'Mon–Sun: 8AM-8PM',
    'footer.phone': '(908) 514-8180',
    'footer.email': 'info@notaryandsignings.com',
    'footer.address1': '180 Talmadge Road, Unit 1380',
    'footer.address2': 'Edison, NJ 08817',
    'footer.bonded_coverage': '$50K Coverage',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    
    // 404 Page
    'notfound.message': 'Oops! Page not found',
    'notfound.return_home': 'Return to Home',
    
    // Authentication
    'auth.title': 'Notary & Signings LLC',
    'auth.subtitle': 'Access your account',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.email_placeholder': 'Enter your email',
    'auth.password_placeholder': 'Enter your password',
    'auth.password_create_placeholder': 'Create a password (min. 6 characters)',
    'auth.signin_button': 'Sign In',
    'auth.signup_button': 'Sign Up',
    'auth.signing_in': 'Signing in...',
    'auth.creating_account': 'Creating account...',
    'auth.dashboard': 'Dashboard',
    'auth.sign_out': 'Sign Out',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to Your Dashboard',
    'dashboard.subtitle': 'Manage your appointments and services',
    'dashboard.account_info': 'Account Info',
    'dashboard.account_description': 'Your account details',
    'dashboard.email': 'Email',
    'dashboard.joined': 'Joined',
    'dashboard.appointments': 'Appointments',
    'dashboard.appointments_description': 'Book and manage appointments',
    'dashboard.appointments_text': 'Schedule your notary services',
    'dashboard.book_appointment': 'Book Appointment',
    'dashboard.documents': 'Documents',
    'dashboard.documents_description': 'Manage your documents',
    'dashboard.documents_text': 'Upload and track documents',
    'dashboard.view_documents': 'View Documents',

    // Booking Pages
    'booking.title': 'Book Your Appointment',
    'booking.subtitle': 'Schedule your professional notary service with convenient online booking',
    'booking.service_selection': 'Service Selection',
    'booking.service_label': 'Service',
    'booking.service_placeholder': 'Choose a service',
    'booking.contact_info': 'Contact Information',
    'booking.full_name': 'Full Name',
    'booking.full_name_placeholder': 'Enter your full name',
    'booking.email': 'Email Address',
    'booking.email_placeholder': 'Enter your email address',
    'booking.phone': 'Phone Number',
    'booking.phone_placeholder': 'Enter your phone number',
    'booking.date_time': 'Select Date and Time',
    'booking.appointment_date': 'Appointment Date',
    'booking.pick_date': 'Pick a date',
    'booking.appointment_time': 'Appointment Time',
    'booking.select_time': 'Select a time',
    'booking.payment_method': 'Payment Method',
    'booking.pay_online': 'Pay Online (Credit/Debit Card)',
    'booking.pay_appointment': 'Pay at Appointment (Cash/Check/Card)',
    'booking.notes': 'Additional Notes',
    'booking.notes_placeholder': 'Any special instructions or additional information...',
    'booking.book_now': 'Book Appointment',
    'booking.loading': 'Booking...',
    'booking.no_slots': 'No available time slots for this date',
    'booking.error.conflict': 'This time slot is no longer available. Please select another time.',
    'booking.error.failed': 'Failed to create booking',
    'booking.error.payment': 'Failed to create payment session',

    // Booking Success
    'success.title': 'Booking Confirmed!',
    'success.subtitle': 'Your appointment has been successfully scheduled',
    'success.appointment_details': 'Appointment Details',
    'success.contact_info': 'Contact Information',
    'success.payment_status': 'Payment Status',
    'success.payment.completed': 'Payment Completed',
    'success.payment.processing': 'Processing Payment',
    'success.payment.due_appointment': 'Payment Due at Appointment',
    'success.payment.failed': 'Payment Failed',
    'success.payment.note': 'Payment will be collected at the time of your appointment. We accept cash, check, and card payments.',
    'success.notes': 'Additional Notes',
    'success.next_steps': 'What\'s Next?',
    'success.before_appointment': 'Before Your Appointment:',
    'success.prepare_docs': 'Prepare all documents that need to be notarized',
    'success.bring_id': 'Bring a valid government-issued photo ID',
    'success.no_sign': 'Do not sign documents before the appointment',
    'success.prepare_payment': 'Prepare payment for the service',
    'success.changes': 'Need to Make Changes?',
    'success.changes_note': 'If you need to reschedule or cancel your appointment, please contact us at least 2 hours in advance.',
    'success.contact_us': 'Contact Us',
    'success.book_another': 'Book Another Appointment',
    'success.confirmation': 'Confirmation Number:',
    'success.not_found': 'Booking Not Found',
    'success.not_found_desc': 'We couldn\'t find your booking. Please check your confirmation email or contact us.',
    'success.book_new': 'Book New Appointment',
    'success.loading': 'Loading...',

    // Validation Messages
    'validation.service_required': 'Service is required',
    'validation.name_min': 'Full name must be at least 2 characters',
    'validation.email_invalid': 'Invalid email address',
    'validation.phone_min': 'Phone number must be at least 10 digits',
    'validation.date_required': 'Appointment date is required',
    'validation.time_required': 'Appointment time is required',

    // Legal Pages
    'legal.last_updated': 'Last updated',
    'legal.privacy_policy': 'Privacy Policy',
    'legal.terms_of_service': 'Terms of Service',
    'legal.cookie_policy': 'Cookie Policy',

    // Privacy Policy
    'privacy.info_collect.title': 'Information We Collect',
    'privacy.info_collect.description': 'At Notary and Signings LLC, we collect information necessary to provide professional notary services in compliance with New Jersey state law:',
    'privacy.info_collect.personal_id': 'Personal Identification: Name, address, phone number, email address, and government-issued photo ID information',
    'privacy.info_collect.doc_info': 'Document Information: Types of documents being notarized (we do not retain copies unless required by law)',
    'privacy.info_collect.transaction': 'Transaction Records: Date, time, location, and type of notarial acts performed as required by NJ notary law',
    'privacy.info_collect.payment': 'Payment Information: Billing address and payment method (credit card information is processed securely and not stored)',
    
    'privacy.info_use.title': 'How We Use Your Information',
    'privacy.info_use.description': 'We use your information solely for:',
    'privacy.info_use.notarial': 'Performing notarial acts in accordance with New Jersey law',
    'privacy.info_use.records': 'Maintaining required notary records and journals',
    'privacy.info_use.scheduling': 'Scheduling appointments and providing mobile services',
    'privacy.info_use.payment': 'Processing payments for services',
    'privacy.info_use.communication': 'Communicating about your notary appointment',
    'privacy.info_use.compliance': 'Complying with legal obligations and regulations',
    
    'privacy.sharing.title': 'Information Sharing and Disclosure',
    'privacy.sharing.description': 'We maintain strict confidentiality and do not sell, rent, or share your personal information except:',
    'privacy.sharing.law': 'When required by law or court order',
    'privacy.sharing.nj_requirements': 'To comply with New Jersey notary record-keeping requirements',
    'privacy.sharing.consent': 'With your express written consent',
    'privacy.sharing.fraud': 'To prevent fraud or protect the safety of individuals',
    'privacy.sharing.providers': 'With service providers who assist in our operations (under strict confidentiality agreements)',
    
    'privacy.retention.title': 'Record Retention',
    'privacy.retention.description': 'In compliance with New Jersey notary law (N.J.S.A. 52:7-10 et seq.), we maintain:',
    'privacy.retention.journals': 'Notary journals for a minimum of 7 years',
    'privacy.retention.acts': 'Records of notarial acts as required by state law',
    'privacy.retention.business': 'Business records for tax and regulatory purposes',
    
    'privacy.security.title': 'Data Security',
    'privacy.security.description': 'We implement appropriate security measures to protect your personal information:',
    'privacy.security.storage': 'Secure storage of physical records in locked, fireproof filing systems',
    'privacy.security.encryption': 'Encrypted digital communications and data storage',
    'privacy.security.access': 'Limited access to personal information on a need-to-know basis',
    'privacy.security.assessments': 'Regular security assessments and updates',
    'privacy.security.disposal': 'Secure disposal of records when retention period expires',
    
    'privacy.rights.title': 'Your Rights',
    'privacy.rights.description': 'You have the right to:',
    'privacy.rights.access': 'Request access to your personal information in our records',
    'privacy.rights.correction': 'Request correction of inaccurate information',
    'privacy.rights.copies': 'Request copies of notarial certificates and records (subject to applicable fees)',
    'privacy.rights.complaints': 'File complaints with the New Jersey Department of Treasury if you believe we have violated notary laws',
    
    'privacy.ron.title': 'Remote Online Notarization (RON)',
    'privacy.ron.description': 'For Remote Online Notarization services, additional privacy considerations apply:',
    'privacy.ron.recordings': 'Video and audio recordings are made and stored as required by New Jersey RON regulations',
    'privacy.ron.verification': 'Identity verification is performed using approved third-party services',
    'privacy.ron.platforms': 'All RON sessions are conducted through secure, encrypted platforms',
    'privacy.ron.records': 'RON records are maintained for the period required by state law',
    
    'privacy.contact.title': 'Contact Information',
    'privacy.contact.description': 'If you have questions about this Privacy Policy or wish to exercise your rights, please contact us:',
    'privacy.contact.company': 'Notary and Signings LLC',
    'privacy.contact.address': '180 Talmadge Road, Unit 1380',
    'privacy.contact.city': 'Edison, NJ 08817',
    'privacy.contact.phone': 'Phone: (908) 514-8180',
    'privacy.contact.email': 'Email: info@notaryandsignings.com',
    
    'privacy.changes.title': 'Changes to This Policy',
    'privacy.changes.description': 'We may update this Privacy Policy to reflect changes in our practices or applicable law. We will notify you of any material changes by posting the updated policy on our website and updating the "Last updated" date. Your continued use of our services after such changes constitutes acceptance of the updated policy.',

    // Terms of Service
    'terms.agreement.title': 'Agreement to Terms',
    'terms.agreement.description': 'By engaging Notary and Signings LLC for notarial services, you agree to be bound by these Terms of Service and all applicable New Jersey state laws and regulations governing notarial acts. These terms constitute a legally binding agreement between you and Notary and Signings LLC.',
    
    'terms.services.title': 'Services Provided',
    'terms.services.description': 'Notary and Signings LLC provides the following services in compliance with New Jersey law:',
    'terms.services.traditional': 'Traditional notarial acts (acknowledgments, jurats, verifications, etc.)',
    'terms.services.mobile': 'Mobile notary services within our service area',
    'terms.services.ron': 'Remote Online Notarization (RON) as authorized by New Jersey law',
    'terms.services.loan': 'Loan signing services for real estate transactions',
    'terms.services.apostille': 'Document authentication and apostille assistance',
    'terms.services.tax': 'Tax preparation services',
    'terms.services.fingerprint': 'Fingerprinting services',
    
    'terms.client_responsibilities.title': 'Client Responsibilities',
    'terms.client_responsibilities.description': 'As a client, you agree to:',
    'terms.client_responsibilities.id': 'Provide valid, government-issued photo identification',
    'terms.client_responsibilities.appear': 'Appear in person (or via approved video technology for RON)',
    'terms.client_responsibilities.understand': 'Understand the contents of documents being notarized',
    'terms.client_responsibilities.willing': 'Sign documents willingly and without coercion',
    'terms.client_responsibilities.accurate': 'Provide accurate information about your identity and the documents',
    'terms.client_responsibilities.payment': 'Pay all fees at the time of service',
    'terms.client_responsibilities.legal': 'Not request any illegal or improper notarial acts',
    
    'terms.identification.title': 'Identification Requirements',
    'terms.identification.description': 'In accordance with New Jersey notary law, acceptable forms of identification include:',
    'terms.identification.drivers': 'Valid driver\'s license',
    'terms.identification.passport': 'Current passport',
    'terms.identification.state_id': 'State-issued identification card',
    'terms.identification.military': 'Military identification',
    'terms.identification.other': 'Other government-issued photo identification deemed acceptable under NJ law',
    'terms.identification.requirements': 'Identification must be current, unexpired, and contain a photograph and signature. We reserve the right to refuse service if adequate identification cannot be provided.',
    
    'terms.fees.title': 'Fees and Payment',
    'terms.fees.description': 'Our fees are established in accordance with New Jersey law and include:',
    'terms.fees.notarial': 'Notarial acts: As permitted by New Jersey statute',
    'terms.fees.mobile': 'Mobile services: $75 per hour including travel time',
    'terms.fees.ron': 'Remote Online Notarization: $35 per document',
    'terms.fees.additional': 'Additional services: As quoted',
    'terms.fees.payment': 'Payment is due at the time of service. We accept cash, check, major credit cards, Venmo, and Zelle. A returned check fee of $35 will be charged for insufficient funds.',
    
    'terms.scheduling.title': 'Scheduling and Cancellations',
    'terms.scheduling.description': 'Appointment scheduling policies:',
    'terms.scheduling.appointment': 'All services are provided by appointment only',
    'terms.scheduling.same_day': 'Same-day appointments available with 2-4 hours notice (subject to availability)',
    'terms.scheduling.cancellation': 'Cancellations must be made at least 2 hours in advance',
    'terms.scheduling.fee': 'Late cancellations or no-shows may be subject to a cancellation fee',
    'terms.scheduling.reschedule': 'We reserve the right to reschedule due to emergencies or unforeseen circumstances',
    
    'terms.refusal.title': 'Refusal of Service',
    'terms.refusal.description': 'We reserve the right to refuse notarial services if:',
    'terms.refusal.no_id': 'Proper identification cannot be provided',
    'terms.refusal.incomplete': 'The document is incomplete or contains blank spaces',
    'terms.refusal.duress': 'The signer appears to be under duress or coercion',
    'terms.refusal.communication': 'The signer cannot communicate directly with the notary',
    'terms.refusal.illegal': 'The notarial act would be illegal or improper',
    'terms.refusal.capacity': 'The signer appears to lack mental capacity',
    'terms.refusal.fraudulent': 'The document appears to be fraudulent',
    
    'terms.liability.title': 'Liability and Insurance',
    'terms.liability.description': 'Notary and Signings LLC maintains professional liability insurance in the amount of $50,000 as required by New Jersey law. Our liability is limited to:',
    'terms.liability.errors': 'Errors in the performance of notarial acts',
    'terms.liability.damages': 'Damages directly resulting from our negligent actions',
    'terms.liability.maximum': 'The maximum coverage amount of our insurance policy',
    'terms.liability.disclaimer': 'We are not responsible for the content, legality, or effect of documents notarized. Clients should consult with appropriate legal counsel regarding document contents and legal implications.',
    
    'terms.privacy.title': 'Privacy and Confidentiality',
    'terms.privacy.description': 'We maintain strict confidentiality regarding all client information and document contents, except as required by law or court order. Our complete Privacy Policy governs the collection, use, and protection of your personal information.',
    
    'terms.disputes.title': 'Dispute Resolution',
    'terms.disputes.description': 'Any disputes arising from our services shall be resolved through:',
    'terms.disputes.negotiation': 'Good faith negotiation between the parties',
    'terms.disputes.mediation': 'Mediation if direct negotiation fails',
    'terms.disputes.arbitration': 'Binding arbitration under New Jersey law if mediation is unsuccessful',
    'terms.disputes.law': 'These terms shall be governed by New Jersey law. Any legal proceedings shall be conducted in the appropriate courts of New Jersey.',
    
    'terms.modifications.title': 'Modifications',
    'terms.modifications.description': 'We reserve the right to modify these Terms of Service at any time. Changes will be posted on our website and will become effective immediately upon posting. Continued use of our services after changes constitutes acceptance of the modified terms.',

    // Cookie Policy
    'cookies.what_are.title': 'What Are Cookies',
    'cookies.what_are.description': 'Cookies are small text files that are stored on your computer or mobile device when you visit our website. They help us provide you with a better experience by remembering your preferences and enabling certain website functionality.',
    
    'cookies.how_use.title': 'How We Use Cookies',
    'cookies.how_use.description': 'Notary and Signings LLC uses cookies for the following purposes:',
    'cookies.how_use.essential': 'Essential Cookies: Required for basic website functionality and security',
    'cookies.how_use.preference': 'Preference Cookies: Remember your language selection and other preferences',
    'cookies.how_use.analytics': 'Analytics Cookies: Help us understand how visitors use our website to improve our services',
    'cookies.how_use.security': 'Security Cookies: Protect against fraudulent activity and enhance website security',
    
    'cookies.types.title': 'Types of Cookies We Use',
    'cookies.types.essential.title': 'Essential Cookies',
    'cookies.types.essential.description': 'These cookies are necessary for the website to function properly and cannot be disabled.',
    'cookies.types.essential.session': 'Session management for appointment booking',
    'cookies.types.essential.auth': 'Authentication for client portal access',
    'cookies.types.essential.security': 'Security tokens for form submissions',
    
    'cookies.types.preference.title': 'Preference Cookies',
    'cookies.types.preference.description': 'These cookies remember your choices and preferences to provide a personalized experience.',
    'cookies.types.preference.language': 'Language preference (English/Spanish)',
    'cookies.types.preference.form': 'Contact form information',
    'cookies.types.preference.accessibility': 'Accessibility settings',
    
    'cookies.types.analytics.title': 'Analytics Cookies',
    'cookies.types.analytics.description': 'These cookies help us understand how visitors interact with our website.',
    'cookies.types.analytics.pages': 'Page views and popular content',
    'cookies.types.analytics.journey': 'User journey and navigation patterns',
    'cookies.types.analytics.requests': 'Service request patterns for business optimization',
    
    'cookies.types.marketing.title': 'Marketing Cookies',
    'cookies.types.marketing.description': 'We do not currently use marketing or advertising cookies. Any future use will be clearly disclosed.',
    
    'cookies.third_party.title': 'Third-Party Cookies',
    'cookies.third_party.description': 'We may use third-party services that set their own cookies:',
    'cookies.third_party.analytics': 'Google Analytics: Website performance and user behavior analysis',
    'cookies.third_party.payment': 'Payment Processors: Secure payment processing for our services',
    'cookies.third_party.ron': 'RON Platforms: Remote online notarization video conferencing',
    'cookies.third_party.scheduling': 'Appointment Scheduling: Online booking system functionality',
    'cookies.third_party.policies': 'These third parties have their own cookie policies, and we encourage you to review them.',
    
    'cookies.duration.title': 'Cookie Duration',
    'cookies.duration.description': 'Cookies are set for different durations based on their purpose:',
    'cookies.duration.session': 'Session Cookies: Deleted when you close your browser',
    'cookies.duration.persistent': 'Persistent Cookies: Remain for a set period (typically 30 days to 2 years)',
    'cookies.duration.preference': 'Preference Cookies: Stored until you change your preferences or clear your browser data',
    
    'cookies.managing.title': 'Managing Your Cookie Preferences',
    'cookies.managing.description': 'You have several options for managing cookies:',
    'cookies.managing.browser.title': 'Browser Settings',
    'cookies.managing.browser.description': 'Most browsers allow you to control cookies through their settings:',
    'cookies.managing.browser.block_all': 'Block all cookies',
    'cookies.managing.browser.block_third': 'Block third-party cookies only',
    'cookies.managing.browser.delete': 'Delete existing cookies',
    'cookies.managing.browser.notifications': 'Receive notifications when cookies are set',
    
    'cookies.managing.specific.title': 'Browser-Specific Instructions',
    'cookies.managing.specific.chrome': 'Chrome: Settings → Privacy and security → Cookies and other site data',
    'cookies.managing.specific.firefox': 'Firefox: Options → Privacy & Security → Cookies and Site Data',
    'cookies.managing.specific.safari': 'Safari: Preferences → Privacy → Cookies and website data',
    'cookies.managing.specific.edge': 'Edge: Settings → Cookies and site permissions → Cookies and stored data',
    
    'cookies.impact.title': 'Impact of Disabling Cookies',
    'cookies.impact.description': 'While you can disable cookies, please note that this may affect your experience on our website:',
    'cookies.impact.reenter': 'You may need to re-enter information on each visit',
    'cookies.impact.features': 'Some features may not work properly',
    'cookies.impact.booking': 'Appointment booking functionality may be limited',
    'cookies.impact.language': 'Language preferences will not be saved',
    'cookies.impact.security': 'Security features may be reduced',
    
    'cookies.data_protection.title': 'Data Protection and Privacy',
    'cookies.data_protection.description': 'Cookie data is handled in accordance with our Privacy Policy and applicable New Jersey and federal data protection laws. We do not sell or share cookie information with third parties except as necessary for website functionality or as required by law.',
    
    'cookies.updates.title': 'Updates to This Cookie Policy',
    'cookies.updates.description': 'We may update this Cookie Policy from time to time to reflect changes in our practices or applicable regulations. We will notify you of any significant changes by posting the updated policy on our website and updating the "Last updated" date.',
    
    'cookies.contact.title': 'Contact Us',
    'cookies.contact.description': 'If you have questions about our use of cookies or this Cookie Policy, please contact us:',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.services': 'Servicios',
    'nav.testimonials': 'Testimonios',
    'nav.faqs': 'Preguntas Frecuentes',
    'nav.contact': 'Contacto',
    'nav.book': 'Reservar Cita',
    
    // Hero Section
    'hero.badge': 'Servicios Profesionales de Confianza',
    'hero.title': 'Servicios',
    'hero.title.highlight': 'Notariales Profesionales',
    'hero.title.end': 'en los que Puedes Confiar',
    'hero.description': 'Desde notario móvil y firmas de préstamos hasta notarización remota en línea y preparación de impuestos, brindamos servicios profesionales integrales con integridad y conveniencia.',
    'hero.feature1': 'Notario Licenciado y Asegurado',
    'hero.feature2': 'Servicios Móviles Disponibles',
    'hero.feature3': 'Notarización Remota en Línea',
    'hero.feature4': 'Citas el Mismo Día',
    'hero.cta.book': 'Reserva tu Cita',
    'hero.cta.phone': '(908) 514-8180',
    'hero.stats.documents': 'Documentos Notarizados',
    'hero.stats.loans': 'Firmas de Préstamos',
    'hero.stats.satisfaction': 'Satisfacción del Cliente',
    'hero.image_alt': 'Servicios notariales profesionales - documentos oficiales y sellos',
    'hero.badge.licensed': 'Licenciado y con Garantía',
    'hero.badge.licensed_desc': 'Servicio Profesional',
    'hero.badge.ron': 'Certificado RON',
    'hero.badge.ron_desc': 'Notarización Remota',
    
    // About Section - Mission and Why Choose Us
    'about.mission.title': 'Nuestra Misión',
    'about.mission.description': 'Proporcionar servicios notariales confiables, profesionales y convenientes mientras mantenemos los más altos estándares de integridad y confidencialidad. Nos esforzamos por hacer que la notarización de documentos sea accesible y libre de estrés para cada cliente.',
    'about.cta': 'Ver Nuestras Credenciales',
    'about.why_choose.title': '¿Por Qué Elegir Notary and Signings LLC?',
    'about.why_choose.subtitle': 'Nuestra dedicación a la excelencia profesional y la satisfacción del cliente nos distingue.',
    'about.why_choose.excellence.title': 'Excelencia Profesional',
    'about.why_choose.excellence.description': 'Licenciados, con garantía y asegurados con educación y entrenamiento continuo',
    'about.why_choose.convenience.title': 'Servicio Conveniente',
    'about.why_choose.convenience.description': 'Servicios móviles, horarios flexibles y opciones de notarización remota',
    'about.why_choose.trust.title': 'Asociación de Confianza',
    'about.why_choose.trust.description': 'Servicio confidencial y confiable con enfoque en construir relaciones a largo plazo',
    'about.verify_credentials': 'Verificar Credenciales de Notario',
    'about.verify_signing_agent': 'Verificar Credenciales de Agente de Firma',
    
    // Services Section
    'services.badge': 'Nuestros Servicios',
    'services.title': 'Soluciones Notariales Integrales',
    'services.subtitle': 'Servicios profesionales diseñados para satisfacer sus necesidades de autenticación y firma de documentos.',
    'services.mobile.title': 'Notario Móvil',
    'services.mobile.description': 'Servicios notariales convenientes en el sitio en su ubicación.',
    'services.mobile.feature1': 'Viajamos a su ubicación',
    'services.mobile.feature2': 'Horarios flexibles',
    'services.mobile.feature3': 'Servicio profesional',
    'services.mobile.feature4': 'Licenciado y con garantía',
    'services.mobile.price': 'Desde $25',
    'services.loan.title': 'Firmas de Préstamos',
    'services.loan.description': 'Especializado en firmas de documentos de préstamos inmobiliarios.',
    'services.loan.feature1': 'Experiencia en bienes raíces',
    'services.loan.feature2': 'Firmas sin errores',
    'services.loan.feature3': 'Servicio el mismo día',
    'services.loan.feature4': 'Aprobado por compañías de títulos',
    'services.loan.price': 'Desde $100',
    'services.ron.title': 'Notarización Remota en Línea',
    'services.ron.description': 'Notarización segura en línea desde cualquier lugar.',
    'services.ron.feature1': 'Plataforma de video segura',
    'services.ron.feature2': 'Firma digital de documentos',
    'services.ron.feature3': 'Verificación de identidad',
    'services.ron.feature4': 'Legalmente conforme',
    'services.ron.price': 'Desde $35',
    'services.apostille.title': 'Servicios de Apostilla',
    'services.apostille.description': 'Autenticación de documentos para uso internacional.',
    'services.apostille.feature1': 'Autenticación internacional',
    'services.apostille.feature2': 'Preparación de documentos',
    'services.apostille.feature3': 'Procesamiento rápido',
    'services.apostille.feature4': 'Manejo seguro',
    'services.apostille.price': 'Desde $50',
    'services.fingerprint.title': 'Servicios de Huellas Dactilares',
    'services.fingerprint.description': 'Huellas dactilares profesionales para verificaciones de antecedentes y licencias.',
    'services.fingerprint.feature1': 'Escáner en Vivo',
    'services.fingerprint.feature2': 'Tarjetas de Tinta',
    'services.fingerprint.feature3': 'Verificación de Antecedentes',
    'services.fingerprint.feature4': 'Solicitudes de Licencia',
     'services.fingerprint.price': 'Desde $20',
     'services.ipen.title': 'Notarización Electrónica en Persona (iPEN)',
     'services.ipen.description': 'Notarización electrónica realizada en persona utilizando tecnología digital segura y firmas electrónicas.',
     'services.ipen.price': '+$40 Extra',
     'services.ipen.addon': 'Disponible con cualquier servicio',
     'services.coming_soon': 'Próximamente',
    'services.tax.individual.title': 'Preparación de Impuestos (Individual)',
    'services.tax.individual.description': 'Servicios profesionales de preparación de impuestos individuales.',
    'services.tax.individual.feature1': 'Declaraciones Individuales',
    'services.tax.individual.feature2': 'Optimización de Deducciones',
    'services.tax.individual.feature3': 'Presentación Electrónica',
    'services.tax.individual.feature4': 'Planificación Fiscal',
    'services.tax.business.title': 'Declaración de Impuestos para Pequeñas Empresas',
    'services.tax.business.description': 'Servicios fiscales integrales para pequeñas empresas.',
    'services.tax.corporate.title': 'Impuestos de Sociedades y Corporaciones',
    'services.tax.corporate.description': 'Preparación avanzada de impuestos para sociedades y corporaciones.',
    'services.tax.review.title': 'Revisión y/o Enmienda de Impuestos',
    'services.tax.review.description': 'Revisión profesional y enmienda de declaraciones de impuestos existentes.',
    
    'services.tax.amendment.title': 'Presentación de Enmienda Fiscal',
    'services.tax.amendment.description': 'Presentar enmiendas para corregir o actualizar declaraciones de impuestos previamente presentadas',
    
    'services.tax.quarterly.title': 'Estimaciones Trimestrales de Impuestos',
    'services.tax.quarterly.description': 'Calcular y presentar pagos trimestrales estimados de impuestos para trabajadores independientes',
    
    'services.tax.prior_year.title': 'Declaraciones de Años Anteriores',
    'services.tax.prior_year.description': 'Preparar y presentar declaraciones de impuestos de años anteriores',
    'services.tax.additional.title': 'Servicios Fiscales Adicionales',
    'services.tax.additional.subtitle': 'Servicios especializados de preparación de impuestos para empresas y declaraciones complejas.',
    'services.book_now': 'Reservar Ahora',
    'services.learn': 'Más Información',
    'services.popular': 'Más Popular',
    'services.areas.title': 'Áreas de Servicio',
    'services.areas.description': 'Servimos con orgullo las siguientes áreas con servicios móviles disponibles:',
    'services.areas.scotch_plains': 'Scotch Plains',
    'services.areas.perth_amboy': 'Perth Amboy',
    'services.areas.new_brunswick': 'New Brunswick',
    'services.areas.piscataway': 'Piscataway',
    'services.areas.plainfield': 'Plainfield',
    'services.areas.south_amboy': 'South Amboy',
    'services.areas.availability': 'Servicio Móvil Disponible',
    'services.areas.same_day': 'Citas el Mismo Día',
    
    // About Section
    'about.badge': 'Acerca de Nosotros',
    'about.title': 'Profesional Licenciado en Quien Puedes Confiar',
    'about.description': 'Con años de experiencia en servicios notariales y autenticación de documentos, brindamos servicios confiables y profesionales con los más altos estándares de integridad y confidencialidad.',
    'about.certification.title': 'Certificaciones Profesionales',
    'about.certification.description': 'Licenciado, con garantía y asegurado con todas las certificaciones estatales requeridas para su tranquilidad.',
    'about.experience.title': 'Años de Experiencia',
    'about.experience.description': 'Amplia experiencia en todo tipo de actos notariales y servicios de autenticación de documentos.',
    'about.mobile.title': 'Servicio Móvil',
    'about.mobile.description': 'Servicios convenientes en el sitio en su hogar, oficina o cualquier ubicación de su elección.',
     'about.stats.certifications': 'Certificaciones Profesionales',
     'about.stats.experience': 'Años de Experiencia',
     'about.stats.documents': 'Documentos Procesados',
     'about.stats.satisfaction': 'Índice de Satisfacción',
     'about.insurance.description': 'Seguro de responsabilidad profesional de $50K para su protección',
     'about.ron.description': 'Certificado en notarización remota a través de plataformas aprobadas',
     'about.loan_signing.title': 'Agente de Firma de Préstamos',
     'about.loan_signing.description': 'Agente de firma de préstamos certificado por NNA con amplia experiencia en bienes raíces',
    
    // Testimonials Section
    'testimonials.badge': 'Testimonios de Clientes',
    'testimonials.title': 'Lo que Dicen Nuestros Clientes',
    'testimonials.subtitle': 'Experiencias reales de clientes satisfechos que confían en nuestros servicios notariales profesionales.',
    'testimonials.stats.professional': 'Servicio Profesional',
    'testimonials.stats.satisfaction': 'Satisfacción del Cliente',
    'testimonials.stats.clients': 'Clientes Felices',
    'testimonials.stats.rating': 'Calificación Promedio',
    'testimonials.cta.title': '¿Listo para Experimentar el Servicio Profesional?',
    'testimonials.cta.description': 'Únete a cientos de clientes satisfechos que confían en nosotros con sus documentos importantes.',
    
    // Individual Testimonials
    'testimonials.client1.name': 'Sarah Johnson',
    'testimonials.client1.role': 'Agente de Bienes Raíces',
    'testimonials.client1.content': 'Notary and Signings LLC ha sido nuestra opción principal para todas las firmas de préstamos. Su profesionalismo y atención al detalle es excepcional. Hacen que el proceso de cierre sea fluido para nuestros clientes.',
    'testimonials.client1.service': 'Firma de Préstamo',
    
    'testimonials.client2.name': 'Michael Chen',
    'testimonials.client2.role': 'Propietario de Pequeña Empresa',
    'testimonials.client2.content': 'El servicio de notario móvil me ahorró mucho tiempo. Vinieron a mi oficina en 2 horas y manejaron todos mis documentos comerciales profesionalmente. ¡Muy recomendado!',
    'testimonials.client2.service': 'Notario Móvil',
    
    'testimonials.client3.name': 'Lisa Rodriguez',
    'testimonials.client3.role': 'Profesional Trabajadora',
    'testimonials.client3.content': 'La notarización remota en línea fue perfecta para mi situación. La videollamada fue segura y profesional, y recibí mis documentos notarizados inmediatamente. ¡Excelente servicio!',
    'testimonials.client3.service': 'Servicio RON',
    
    'testimonials.client4.name': 'David Thompson',
    'testimonials.client4.role': 'Jubilado',
    'testimonials.client4.content': 'Necesitaba mi declaración de impuestos preparada y documentos notarizados. Manejaron todo con cuidado y explicaron cada paso. Servicio confiable y de confianza.',
    'testimonials.client4.service': 'Preparación de Impuestos',
    
    'testimonials.client5.name': 'Jennifer Park',
    'testimonials.client5.role': 'Trabajadora de la Salud',
    'testimonials.client5.content': 'Servicio rápido de huellas dactilares para la renovación de mi licencia. Configuración profesional y respuesta rápida. Hicieron que el proceso fuera fácil y sin estrés.',
    'testimonials.client5.service': 'Huellas Dactilares',
    
    'testimonials.client6.name': 'Robert Williams',
    'testimonials.client6.role': 'Estudiante Internacional',
    'testimonials.client6.content': 'Necesitaba servicios de apostilla para mis documentos para usar en el extranjero. Manejaron todo el proceso y me mantuvieron informado durante todo el proceso. ¡Excelente servicio!',
    'testimonials.client6.service': 'Apostilla',
    
    // FAQ Page
    'faqs.badge': 'Preguntas Frecuentes',
    'faqs.title': '¿Cómo Podemos Ayudarte?',
    'faqs.subtitle': 'Encuentra respuestas a las preguntas más comunes sobre nuestros servicios notariales, precios y procesos.',
    'faqs.contact.title': '¿Aún Tienes Preguntas?',
    'faqs.contact.description': 'Si no puedes encontrar la respuesta que buscas, no dudes en contactarnos directamente. ¡Estamos aquí para ayudar!',
    
    // FAQ Categories
    'faqs.general.title': 'Preguntas Generales',
    'faqs.general.q1.question': '¿Qué es un notario público y qué hace?',
    'faqs.general.q1.answer': 'Un notario público es un funcionario nombrado por el estado que sirve como testigo imparcial de la firma de documentos importantes. Verificamos la identidad de los firmantes, nos aseguramos de que entiendan lo que están firmando y confirmamos que firmen voluntariamente sin coerción.',
    'faqs.general.q2.question': '¿Qué documentos necesito traer para la notarización?',
    'faqs.general.q2.answer': 'Necesitarás:\n• Una identificación con foto válida emitida por el gobierno (licencia de conducir, pasaporte o identificación estatal)\n• El/los documento(s) sin firmar para notarizar\n• Cualquier documentación adicional especificada por los requisitos del documento',
    'faqs.general.q3.question': '¿Están licenciados y asegurados?',
    'faqs.general.q3.answer': 'Sí, somos notarios públicos completamente licenciados en el estado de Nueva Jersey, con garantía y portamos $100,000 en seguro de responsabilidad profesional para su protección y tranquilidad.',
    'faqs.general.q4.question': '¿Cuáles son sus horarios comerciales?',
    'faqs.general.q4.answer': 'Operamos de lunes a domingo, de 8AM a 8PM, solo con cita previa. Ofrecemos horarios flexibles para acomodar su agenda ocupada, incluyendo citas nocturnas y de fin de semana.',
    
    'faqs.mobile.title': 'Servicios de Notario Móvil',
    'faqs.mobile.q1.question': '¿Viajan a mi ubicación?',
    'faqs.mobile.q1.answer': '¡Sí! Proporcionamos servicios de notario móvil dentro de 25 millas de Edison, NJ. Iremos a su hogar, oficina, hospital o cualquier ubicación conveniente por una tarifa de viaje adicional.',
    'faqs.mobile.q2.question': '¿Cuánto cuesta el servicio móvil?',
    'faqs.mobile.q2.answer': 'El servicio de notario móvil es $75 por 1 hora, que incluye tiempo de viaje y notarización de sus documentos. El tiempo adicional se factura en incrementos de 15 minutos.',
    'faqs.mobile.q3.question': '¿Qué tan rápido pueden venir a verme?',
    'faqs.mobile.q3.answer': 'Típicamente podemos programar citas el mismo día con 2-4 horas de aviso. Para solicitudes urgentes, por favor llámenos directamente al (908) 514-8180.',
    
    'faqs.ron.title': 'Notarización Remota en Línea (RON)',
    'faqs.ron.q1.question': '¿Qué es la Notarización Remota en Línea?',
    'faqs.ron.q1.answer': 'RON le permite obtener documentos notarizados en línea a través de una videoconferencia segura. Puede estar en cualquier lugar del mundo mientras verificamos su identidad digitalmente y presenciamos su firma electrónica.',
    'faqs.ron.q2.question': '¿Qué necesito para RON?',
    'faqs.ron.q2.answer': 'Necesitará:\n• Una computadora, tableta o teléfono inteligente con cámara y micrófono\n• Conexión estable a internet\n• Identificación con foto válida emitida por el gobierno\n• El documento en formato PDF (podemos ayudar a convertir si es necesario)',
    'faqs.ron.q3.question': '¿Es RON legalmente válido?',
    'faqs.ron.q3.answer': 'Sí, RON es legalmente válido y reconocido en Nueva Jersey y muchos otros estados. El documento notarizado electrónicamente tiene el mismo peso legal que una notarización tradicional en papel.',
    
    'faqs.loan.title': 'Servicios de Firma de Préstamos',
    'faqs.loan.q1.question': '¿Qué es un agente de firma de préstamos?',
    'faqs.loan.q1.answer': 'Un agente de firma de préstamos es un notario especialmente entrenado que maneja la firma de documentos de préstamos inmobiliarios. Nos aseguramos de que todos los documentos se firmen correctamente y se devuelvan a la compañía de títulos o prestamista prontamente.',
    'faqs.loan.q2.question': '¿Cuánto tiempo toma una firma de préstamo?',
    'faqs.loan.q2.answer': 'La mayoría de las firmas de préstamos toman 1 hora para completarse. Permitimos tiempo suficiente para revisar documentos, responder preguntas y asegurar que todo se firme correctamente.',
    'faqs.loan.q3.question': '¿Trabajan con todas las compañías de títulos y prestamistas?',
    'faqs.loan.q3.answer': 'Sí, trabajamos con compañías de títulos, prestamistas y servicios de firma en todo Nueva Jersey. Estamos aprobados por las principales compañías de títulos y mantenemos los más altos estándares de profesionalismo.',
    
    'faqs.pricing.title': 'Precios y Pago',
    'faqs.pricing.q1.question': '¿Qué formas de pago aceptan?',
    'faqs.pricing.q1.answer': 'Aceptamos efectivo, cheque, Venmo, Zelle y todas las principales tarjetas de crédito. El pago vence al momento del servicio.',
    'faqs.pricing.q2.question': '¿Hay tarifas adicionales?',
    'faqs.pricing.q2.answer': 'Nuestros precios son transparentes. El servicio móvil incluye viaje dentro de 25 millas. Para ubicaciones más allá de 25 millas, hay una tarifa adicional por milla. El servicio urgente (menos de 2 horas de aviso) puede incluir una tarifa adicional.',
    'faqs.pricing.q3.question': '¿Ofrecen descuentos para múltiples documentos?',
    'faqs.pricing.q3.answer': 'Sí, ofrecemos precios competitivos para múltiples documentos durante la misma cita. Contáctenos para una cotización personalizada para paquetes grandes de documentos.',
    
    // Contact Section
    'contact.badge': 'Contáctanos',
    'contact.title': '¿Listo para Comenzar?',
    'contact.subtitle': 'Contáctanos hoy para programar tu cita notarial u obtener respuestas a tus preguntas.',
     'contact.info.location': 'Nuestra Ubicación',
     'contact.info.location.address': '180 Talmadge Road, Unit 1380, Edison, NJ 08817',
     'contact.info.location.description': 'Servicios móviles dentro de 25 millas',
     'contact.info.phone': 'Número de Teléfono',
     'contact.info.phone.description': 'Llámanos para asistencia inmediata',
     'contact.info.email': 'Dirección de Correo',
     'contact.info.email.description': 'Envíanos tus preguntas en cualquier momento',
    'contact.info.hours': 'Horario Comercial',
    'contact.info.hours.schedule': 'Lun-Dom: 8AM-8PM',
    'contact.info.hours.description': 'Disponibilidad de lunes a domingo',
     'contact.form.title': 'Envíanos un Mensaje',
     'contact.form.first_name': 'Nombre',
     'contact.form.last_name': 'Apellido', 
     'contact.form.name': 'Nombre Completo',
     'contact.form.preferred_date': 'Fecha Preferida',
     'contact.form.email': 'Correo Electrónico',
     'contact.form.phone': 'Número de Teléfono',
    'contact.form.service': 'Servicio Necesario',
    'contact.form.service.mobile': 'Notario Móvil',
    'contact.form.service.loan': 'Firma de Préstamo',
    'contact.form.service.ron': 'Notarización Remota',
    'contact.form.service.apostille': 'Servicio de Apostilla',
    'contact.form.service.other': 'Otros Servicios',
    'contact.form.timing': 'Horario Preferido',
    'contact.form.timing.morning': 'Mañana (8AM-12PM)',
    'contact.form.timing.afternoon': 'Tarde (12PM-5PM)',
    'contact.form.timing.evening': 'Noche (5PM-8PM)',
    'contact.form.timing.flexible': 'Horario Flexible',
     'contact.form.message': 'Mensaje',
     'contact.form.message_placeholder': 'Por favor proporcione detalles sobre sus necesidades notariales, número de documentos, preferencias de ubicación o cualquier requisito especial...',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.response': 'Responderemos dentro de 2 horas durante el horario comercial.',
    'contact.hours.monday': 'Lunes - Viernes',
    'contact.hours.saturday': 'Sábado',
    'contact.hours.sunday': 'Domingo',
    'contact.hours.appointment': 'Solo con cita previa',
    'contact.hours.appointment_only': 'Solo con Cita Previa',
    'contact.emergency.title': 'Servicios Profesionales',
    'contact.emergency.description': 'Servicios notariales licenciados, con garantía y asegurados con programación flexible para satisfacer sus necesidades.',
    
    // Footer
    'footer.company': 'Notary & Signings LLC',
    'footer.description': 'Servicios notariales profesionales en los que puedes confiar. Licenciado, con garantía y asegurado para tu tranquilidad. Sirviendo a la comunidad con integridad y excelencia.',
    'footer.quick_links': 'Enlaces Rápidos',
     'footer.services': 'Nuestros Servicios',
     'footer.services.fingerprinting': 'Servicios de Huellas Dactilares (Próximamente)',
     'footer.services.tax_preparation': 'Preparación de Impuestos',
    'footer.credentials': 'Credenciales Profesionales',
    'footer.licensed': 'Notario Licenciado',
    'footer.licensed_desc': 'Certificado por el Estado',
    'footer.bonded': 'Con Garantía y Asegurado',
    'footer.bonded_desc': 'Cobertura de $100K',
    'footer.ron_certified': 'Certificado RON',
    'footer.ron_desc': 'Notarización Remota',
    'footer.verify_notary': 'Verificar Credenciales de Notario',
    'footer.verify_signing': 'Verificar Credenciales de Agente de Firma',
    'footer.professional_services': 'Servicios Profesionales',
    'footer.professional_desc': 'Servicios notariales licenciados, con garantía y asegurados con programación flexible.',
    'footer.schedule': 'Programar Cita',
    'footer.copyright': '© 2025 Notary and Signings. Todos los derechos reservados.',
    'footer.business_hours': 'Lun–Dom: 8AM-8PM',
    'footer.phone': '(908) 514-8180',
    'footer.email': 'info@notaryandsignings.com',
    'footer.address1': '180 Talmadge Road, Unit 1380',
    'footer.address2': 'Edison, NJ 08817',
    'footer.bonded_coverage': 'Cobertura de $50K',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.cookies': 'Política de Cookies',
    
    // 404 Page
    'notfound.message': '¡Oops! Página no encontrada',
    'notfound.return_home': 'Volver al Inicio',
    
    // Authentication
    'auth.title': 'Notary & Signings LLC',
    'auth.subtitle': 'Accede a tu cuenta',
    'auth.signin': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.email_placeholder': 'Ingresa tu correo electrónico',
    'auth.password_placeholder': 'Ingresa tu contraseña',
    'auth.password_create_placeholder': 'Crea una contraseña (mín. 6 caracteres)',
    'auth.signin_button': 'Iniciar Sesión',
    'auth.signup_button': 'Registrarse',
    'auth.signing_in': 'Iniciando sesión...',
    'auth.creating_account': 'Creando cuenta...',
    'auth.dashboard': 'Panel de Control',
    'auth.sign_out': 'Cerrar Sesión',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido a tu Panel de Control',
    'dashboard.subtitle': 'Gestiona tus citas y servicios',
    'dashboard.account_info': 'Información de la Cuenta',
    'dashboard.account_description': 'Detalles de tu cuenta',
    'dashboard.email': 'Correo Electrónico',
    'dashboard.joined': 'Registrado',
    'dashboard.appointments': 'Citas',
    'dashboard.appointments_description': 'Reserva y gestiona citas',
    'dashboard.appointments_text': 'Programa tus servicios notariales',
    'dashboard.book_appointment': 'Reservar Cita',
    'dashboard.documents': 'Documentos',
    'dashboard.documents_description': 'Gestiona tus documentos',
    'dashboard.documents_text': 'Sube y rastrea documentos',
    'dashboard.view_documents': 'Ver Documentos',

    // Booking Pages
    'booking.title': 'Reserve Su Cita',
    'booking.subtitle': 'Programe su servicio notarial profesional con reserva en línea conveniente',
    'booking.service_selection': 'Seleccionar Servicio',
    'booking.service_label': 'Servicio',
    'booking.service_placeholder': 'Elija un servicio',
    'booking.contact_info': 'Información de Contacto',
    'booking.full_name': 'Nombre Completo',
    'booking.full_name_placeholder': 'Ingrese su nombre completo',
    'booking.email': 'Correo Electrónico',
    'booking.email_placeholder': 'Ingrese su correo electrónico',
    'booking.phone': 'Número de Teléfono',
    'booking.phone_placeholder': 'Ingrese su número de teléfono',
    'booking.date_time': 'Seleccionar Fecha y Hora',
    'booking.appointment_date': 'Fecha de la Cita',
    'booking.pick_date': 'Elegir una fecha',
    'booking.appointment_time': 'Hora de la Cita',
    'booking.select_time': 'Seleccionar una hora',
    'booking.payment_method': 'Método de Pago',
    'booking.pay_online': 'Pagar en Línea (Tarjeta de Crédito/Débito)',
    'booking.pay_appointment': 'Pagar en la Cita (Efectivo/Cheque/Tarjeta)',
    'booking.notes': 'Notas Adicionales',
    'booking.notes_placeholder': 'Cualquier instrucción especial o información adicional...',
    'booking.book_now': 'Reservar Cita',
    'booking.loading': 'Reservando...',
    'booking.no_slots': 'No hay horarios disponibles para esta fecha',
    'booking.error.conflict': 'Este horario ya no está disponible. Por favor seleccione otra hora.',
    'booking.error.failed': 'No se pudo crear la reserva',
    'booking.error.payment': 'No se pudo crear la sesión de pago',

    // Booking Success
    'success.title': '¡Reserva Confirmada!',
    'success.subtitle': 'Su cita ha sido programada exitosamente',
    'success.appointment_details': 'Detalles de la Cita',
    'success.contact_info': 'Información de Contacto',
    'success.payment_status': 'Estado del Pago',
    'success.payment.completed': 'Pago Completado',
    'success.payment.processing': 'Procesando Pago',
    'success.payment.due_appointment': 'Pago Debido en la Cita',
    'success.payment.failed': 'Pago Fallido',
    'success.payment.note': 'El pago se cobrará en el momento de su cita. Aceptamos efectivo, cheque y pagos con tarjeta.',
    'success.notes': 'Notas Adicionales',
    'success.next_steps': '¿Qué Sigue?',
    'success.before_appointment': 'Antes de Su Cita:',
    'success.prepare_docs': 'Prepare todos los documentos que necesitan ser notarizados',
    'success.bring_id': 'Traiga una identificación con foto emitida por el gobierno válida',
    'success.no_sign': 'No firme los documentos antes de la cita',
    'success.prepare_payment': 'Prepare el pago para el servicio',
    'success.changes': '¿Necesita Hacer Cambios?',
    'success.changes_note': 'Si necesita reprogramar o cancelar su cita, por favor contáctenos con al menos 2 horas de anticipación.',
    'success.contact_us': 'Contáctanos',
    'success.book_another': 'Reservar Otra Cita',
    'success.confirmation': 'Número de Confirmación:',
    'success.not_found': 'Reserva No Encontrada',
    'success.not_found_desc': 'No pudimos encontrar su reserva. Por favor revise su correo de confirmación o contáctenos.',
    'success.book_new': 'Reservar Nueva Cita',
    'success.loading': 'Cargando...',

    // Validation Messages
    'validation.service_required': 'El servicio es requerido',
    'validation.name_min': 'El nombre completo debe tener al menos 2 caracteres',
    'validation.email_invalid': 'Dirección de correo electrónico inválida',
    'validation.phone_min': 'El número de teléfono debe tener al menos 10 dígitos',
    'validation.date_required': 'La fecha de la cita es requerida',
    'validation.time_required': 'La hora de la cita es requerida',
  }
};