import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.testimonials': 'Testimonials',
    'nav.faqs': 'FAQs',
    'nav.contact': 'Contact',
    'nav.book': 'Book Appointment',
    
    // Hero Section
    'hero.badge': 'Trusted Professional Services',
    'hero.title': 'Professional',
    'hero.title.highlight': 'Notary Services',
    'hero.title.end': 'You Can Trust',
    'hero.description': 'From mobile notary and loan signings to remote online notarization and tax preparation, we provide comprehensive professional services with integrity and convenience.',
    'hero.feature1': 'Licensed & Insured Notary',
    'hero.feature2': 'Mobile Services Available',
    'hero.feature3': 'Remote Online Notarization',
    'hero.feature4': 'Same-Day Appointments',
    'hero.cta.book': 'Book Your Appointment',
    'hero.cta.phone': '(908) 514-8180',
    'hero.stats.documents': 'Documents Notarized',
    'hero.stats.loans': 'Loan Signings',
    'hero.stats.satisfaction': 'Client Satisfaction',
    'hero.image_alt': 'Professional notary services - official documents and seals',
    'hero.badge.licensed': 'Licensed & Bonded',
    'hero.badge.licensed_desc': 'Professional Service',
    'hero.badge.ron': 'RON Certified',
    'hero.badge.ron_desc': 'Remote Notarization',
    
    // About Section - Mission and Why Choose Us
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To provide reliable, professional, and convenient notary services while maintaining the highest standards of integrity and confidentiality. We strive to make document notarization accessible and stress-free for every client.',
    'about.cta': 'View Our Credentials',
    'about.why_choose.title': 'Why Choose Notary and Signings LLC?',
    'about.why_choose.subtitle': 'Our dedication to professional excellence and client satisfaction sets us apart.',
    'about.why_choose.excellence.title': 'Professional Excellence',
    'about.why_choose.excellence.description': 'Licensed, bonded, and insured with continuous education and training',
    'about.why_choose.convenience.title': 'Convenient Service',
    'about.why_choose.convenience.description': 'Mobile services, flexible scheduling, and remote notarization options',
    'about.why_choose.trust.title': 'Trusted Partnership',
    'about.why_choose.trust.description': 'Confidential, reliable service with a focus on building long-term relationships',
    'about.verify_credentials': 'Verify Notary Credentials',
    'about.verify_signing_agent': 'Verify Signing Agent Credentials',
    
    // Services Section
    'services.badge': 'Our Services',
    'services.title': 'Comprehensive Notary Solutions',
    'services.subtitle': 'Professional services tailored to meet your document authentication and signing needs.',
    'services.mobile.title': 'Mobile Notary',
    'services.mobile.description': 'Convenient on-site notary services at your location.',
    'services.mobile.feature1': 'Travel to your location',
    'services.mobile.feature2': 'Flexible scheduling',
    'services.mobile.feature3': 'Professional service',
    'services.mobile.feature4': 'Licensed & bonded',
    'services.mobile.price': 'From $25',
    'services.loan.title': 'Loan Signings',
    'services.loan.description': 'Specialized in real estate loan document signings.',
    'services.loan.feature1': 'Real estate expertise',
    'services.loan.feature2': 'Error-free signings',
    'services.loan.feature3': 'Same-day service',
    'services.loan.feature4': 'Title company approved',
    'services.loan.price': 'From $100',
    'services.ron.title': 'Remote Online Notarization',
    'services.ron.description': 'Secure online notarization from anywhere.',
    'services.ron.feature1': 'Secure video platform',
    'services.ron.feature2': 'Digital document signing',
    'services.ron.feature3': 'Identity verification',
    'services.ron.feature4': 'Legally compliant',
    'services.ron.price': 'From $35',
    'services.apostille.title': 'Apostille Services',
    'services.apostille.description': 'Document authentication for international use.',
    'services.apostille.feature1': 'International authentication',
    'services.apostille.feature2': 'Document preparation',
    'services.apostille.feature3': 'Fast processing',
    'services.apostille.feature4': 'Secure handling',
    'services.apostille.price': 'From $50',
    'services.fingerprint.title': 'Fingerprinting Services',
    'services.fingerprint.description': 'Professional fingerprinting for background checks and licensing.',
    'services.fingerprint.feature1': 'Live Scan',
    'services.fingerprint.feature2': 'INK Cards',
    'services.fingerprint.feature3': 'Background Checks',
    'services.fingerprint.feature4': 'License Applications',
     'services.fingerprint.price': 'From $20',
     'services.ipen.title': 'In-Person Electronic Notarization (iPEN)',
     'services.ipen.description': 'Electronic notarization performed in-person using secure digital technology and electronic signatures.',
     'services.ipen.feature1': 'Electronic signatures',
     'services.ipen.feature2': 'Digital notary seal',
     'services.ipen.feature3': 'Secure authentication',
     'services.ipen.feature4': 'Immediate processing',
     'services.tax.individual.title': 'Tax Preparation (Individual)',
    'services.tax.individual.description': 'Professional individual tax preparation services.',
    'services.tax.individual.feature1': 'Individual Returns',
    'services.tax.individual.feature2': 'Deduction Optimization',
    'services.tax.individual.feature3': 'E-Filing',
    'services.tax.individual.feature4': 'Tax Planning',
    'services.tax.business.title': 'Small Business Tax Filing',
    'services.tax.business.description': 'Comprehensive tax services for small businesses.',
    'services.tax.corporate.title': 'Partnership & Corporate Taxes',
    'services.tax.corporate.description': 'Advanced tax preparation for partnerships and corporations.',
    'services.tax.review.title': 'Tax Review and/or Amendment',
    'services.tax.review.description': 'Professional review and amendment of existing tax returns.',
    'services.tax.additional.title': 'Additional Tax Services',
    'services.tax.additional.subtitle': 'Specialized tax preparation services for businesses and complex returns.',
    'services.book_now': 'Book Now',
    'services.learn': 'Learn More',
    'services.popular': 'Most Popular',
    'services.areas.title': 'Service Areas',
    'services.areas.description': 'We proudly serve the following areas with mobile services available:',
    'services.areas.scotch_plains': 'Scotch Plains',
    'services.areas.perth_amboy': 'Perth Amboy',
    'services.areas.new_brunswick': 'New Brunswick',
    'services.areas.piscataway': 'Piscataway',
    'services.areas.plainfield': 'Plainfield',
    'services.areas.south_amboy': 'South Amboy',
    'services.areas.availability': 'Mobile Service Available',
    'services.areas.same_day': 'Same-Day Appointments',
    
    // About Section
    'about.badge': 'About Us',
    'about.title': 'Licensed Professional You Can Trust',
    'about.description': 'With years of experience in notary services and document authentication, we provide reliable, professional services with the highest standards of integrity and confidentiality.',
    'about.certification.title': 'Professional Certifications',
    'about.certification.description': 'Licensed, bonded, and insured with all required state certifications for your peace of mind.',
    'about.experience.title': 'Years of Experience',
    'about.experience.description': 'Extensive experience in all types of notarial acts and document authentication services.',
    'about.mobile.title': 'Mobile Service',
    'about.mobile.description': 'Convenient on-site services at your home, office, or any location of your choice.',
    'about.stats.certifications': 'Professional Certifications',
    'about.stats.experience': 'Years Experience',
    'about.stats.documents': 'Documents Processed',
    'about.stats.satisfaction': 'Satisfaction Rate',
    
    // Testimonials Section
    'testimonials.badge': 'Client Testimonials',
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': 'Real experiences from satisfied clients who trust our professional notary services.',
    'testimonials.stats.professional': 'Professional Service',
    'testimonials.stats.satisfaction': 'Client Satisfaction',
    'testimonials.stats.clients': 'Happy Clients',
    'testimonials.stats.rating': 'Average Rating',
    'testimonials.cta.title': 'Ready to Experience Professional Service?',
    'testimonials.cta.description': 'Join hundreds of satisfied clients who trust us with their important documents.',
    
    // Individual Testimonials
    'testimonials.client1.name': 'Sarah Johnson',
    'testimonials.client1.role': 'Real Estate Agent',
    'testimonials.client1.content': 'Notary and Signings LLC has been our go-to for all loan signings. Their professionalism and attention to detail is outstanding. They make the closing process smooth for our clients.',
    'testimonials.client1.service': 'Loan Signing',
    
    'testimonials.client2.name': 'Michael Chen',
    'testimonials.client2.role': 'Small Business Owner',
    'testimonials.client2.content': 'The mobile notary service saved me so much time. They came to my office within 2 hours and handled all my business documents professionally. Highly recommend!',
    'testimonials.client2.service': 'Mobile Notary',
    
    'testimonials.client3.name': 'Lisa Rodriguez',
    'testimonials.client3.role': 'Working Professional',
    'testimonials.client3.content': 'Remote online notarization was perfect for my situation. The video call was secure and professional, and I received my notarized documents immediately. Great service!',
    'testimonials.client3.service': 'RON Service',
    
    'testimonials.client4.name': 'David Thompson',
    'testimonials.client4.role': 'Retiree',
    'testimonials.client4.content': 'Needed my tax return prepared and documents notarized. They handled everything with care and explained each step. Trustworthy and reliable service.',
    'testimonials.client4.service': 'Tax Preparation',
    
    'testimonials.client5.name': 'Jennifer Park',
    'testimonials.client5.role': 'Healthcare Worker',
    'testimonials.client5.content': 'Fast fingerprinting service for my license renewal. Professional setup and quick turnaround. They made the process easy and stress-free.',
    'testimonials.client5.service': 'Fingerprinting',
    
    'testimonials.client6.name': 'Robert Williams',
    'testimonials.client6.role': 'International Student',
    'testimonials.client6.content': 'Needed apostille services for my documents to be used abroad. They handled the entire process and kept me updated throughout. Excellent service!',
    'testimonials.client6.service': 'Apostille',
    
    // FAQ Page
    'faqs.badge': 'Frequently Asked Questions',
    'faqs.title': 'How Can We Help You?',
    'faqs.subtitle': 'Find answers to the most common questions about our notary services, pricing, and processes.',
    'faqs.contact.title': 'Still Have Questions?',
    'faqs.contact.description': 'If you can\'t find the answer you\'re looking for, don\'t hesitate to reach out to us directly. We\'re here to help!',
    
    // FAQ Categories
    'faqs.general.title': 'General Questions',
    'faqs.general.q1.question': 'What is a notary public and what do they do?',
    'faqs.general.q1.answer': 'A notary public is a state-appointed official who serves as an impartial witness to the signing of important documents. We verify the identity of signers, ensure they understand what they\'re signing, and confirm they\'re signing willingly without coercion.',
    'faqs.general.q2.question': 'What documents do I need to bring for notarization?',
    'faqs.general.q2.answer': 'You\'ll need:\n• A valid government-issued photo ID (driver\'s license, passport, or state ID)\n• The unsigned document(s) to be notarized\n• Any additional documentation specified by the document requirements',
    'faqs.general.q3.question': 'Are you licensed and insured?',
    'faqs.general.q3.answer': 'Yes, we are fully licensed notaries public in the state of New Jersey, bonded, and carry $50,000 in professional liability insurance for your protection and peace of mind.',
    'faqs.general.q4.question': 'What are your business hours?',
    'faqs.general.q4.answer': 'We operate Monday through Sunday, 8AM to 8PM, by appointment only. We offer flexible scheduling to accommodate your busy schedule, including evening and weekend appointments.',
    
    'faqs.mobile.title': 'Mobile Notary Services',
    'faqs.mobile.q1.question': 'Do you travel to my location?',
    'faqs.mobile.q1.answer': 'Yes! We provide mobile notary services within 25 miles of Edison, NJ. We\'ll come to your home, office, hospital, or any convenient location for an additional travel fee.',
    'faqs.mobile.q2.question': 'How much does mobile service cost?',
    'faqs.mobile.q2.answer': 'Mobile notary service is $75 for 1 hour, which includes travel time and notarization of your documents. Additional time is billed in 15-minute increments.',
    'faqs.mobile.q3.question': 'How quickly can you come to me?',
    'faqs.mobile.q3.answer': 'We typically can schedule same-day appointments with 2-4 hours notice. For urgent requests, please call us directly at (908) 514-8180.',
    
    'faqs.ron.title': 'Remote Online Notarization (RON)',
    'faqs.ron.q1.question': 'What is Remote Online Notarization?',
    'faqs.ron.q1.answer': 'RON allows you to get documents notarized online through a secure video conference. You can be anywhere in the world while we verify your identity digitally and witness your electronic signature.',
    'faqs.ron.q2.question': 'What do I need for RON?',
    'faqs.ron.q2.answer': 'You\'ll need:\n• A computer, tablet, or smartphone with camera and microphone\n• Stable internet connection\n• Valid government-issued photo ID\n• The document in PDF format (we can help convert if needed)',
    'faqs.ron.q3.question': 'Is RON legally valid?',
    'faqs.ron.q3.answer': 'Yes, RON is legally valid and recognized in New Jersey and many other states. The electronically notarized document has the same legal weight as a traditional paper notarization.',
    
    'faqs.loan.title': 'Loan Signing Services',
    'faqs.loan.q1.question': 'What is a loan signing agent?',
    'faqs.loan.q1.answer': 'A loan signing agent is a specially trained notary who handles the signing of real estate loan documents. We ensure all documents are signed correctly and returned to the title company or lender promptly.',
    'faqs.loan.q2.question': 'How long does a loan signing take?',
    'faqs.loan.q2.answer': 'Most loan signings take 1 hour to complete. We allow sufficient time to review documents, answer questions, and ensure everything is signed properly.',
    'faqs.loan.q3.question': 'Do you work with all title companies and lenders?',
    'faqs.loan.q3.answer': 'Yes, we work with title companies, lenders, and signing services throughout New Jersey. We\'re approved by major title companies and maintain the highest standards of professionalism.',
    
    'faqs.pricing.title': 'Pricing & Payment',
    'faqs.pricing.q1.question': 'What forms of payment do you accept?',
    'faqs.pricing.q1.answer': 'We accept cash, check, Venmo, Zelle, and all major credit cards. Payment is due at the time of service.',
    'faqs.pricing.q2.question': 'Are there any additional fees?',
    'faqs.pricing.q2.answer': 'Our pricing is transparent. Mobile service includes travel within 25 miles. For locations beyond 25 miles, there\'s an additional mileage fee. Rush service (less than 2 hours notice) may include an additional fee.',
    'faqs.pricing.q3.question': 'Do you offer discounts for multiple documents?',
    'faqs.pricing.q3.answer': 'Yes, we offer competitive pricing for multiple documents during the same appointment. Contact us for a custom quote for large document packages.',
    
    // Contact Section
    'contact.badge': 'Contact Us',
    'contact.title': 'Ready to Get Started?',
    'contact.subtitle': 'Contact us today to schedule your notary appointment or get answers to your questions.',
    'contact.info.location': 'Our Location',
    'contact.info.location.address': '180 Talmadge Road, Unit 1380, Edison, NJ 08817',
    'contact.info.phone': 'Phone Number',
    'contact.info.email': 'Email Address',
    'contact.info.hours': 'Business Hours',
    'contact.info.hours.schedule': 'Mon-Sun: 8AM-8PM',
    'contact.info.hours.description': 'Monday through Sunday availability',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.service': 'Service Needed',
    'contact.form.service.mobile': 'Mobile Notary',
    'contact.form.service.loan': 'Loan Signing',
    'contact.form.service.ron': 'Remote Notarization',
    'contact.form.service.apostille': 'Apostille Service',
    'contact.form.service.other': 'Other Services',
    'contact.form.timing': 'Preferred Timing',
    'contact.form.timing.morning': 'Morning (8AM-12PM)',
    'contact.form.timing.afternoon': 'Afternoon (12PM-5PM)',
    'contact.form.timing.evening': 'Evening (5PM-8PM)',
    'contact.form.timing.flexible': 'Flexible Timing',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.response': "We'll respond within 2 hours during business hours.",
    'contact.hours.monday': 'Monday - Friday',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.appointment': 'By appointment only',
    'contact.hours.appointment_only': 'By Appointment Only',
    'contact.emergency.title': 'Professional Services',
    'contact.emergency.description': 'Licensed, bonded, and insured notary services with flexible scheduling to meet your needs.',
    
    // Footer
    'footer.company': 'Notary & Signings LLC',
    'footer.description': 'Professional notary services you can trust. Licensed, bonded, and insured for your peace of mind. Serving the community with integrity and excellence.',
    'footer.quick_links': 'Quick Links',
    'footer.services': 'Our Services',
    'footer.credentials': 'Professional Credentials',
    'footer.licensed': 'Licensed Notary',
    'footer.licensed_desc': 'State Certified',
    'footer.bonded': 'Bonded & Insured',
    'footer.bonded_desc': '$100K Coverage',
    'footer.ron_certified': 'RON Certified',
    'footer.ron_desc': 'Remote Notarization',
    'footer.verify_notary': 'Verify Notary Credentials',
    'footer.verify_signing': 'Verify Signing Agent Credentials',
    'footer.professional_services': 'Professional Services',
    'footer.professional_desc': 'Licensed, bonded, and insured notary services with flexible scheduling.',
    'footer.schedule': 'Schedule Appointment',
    'footer.copyright': '© 2024 Notary and Signings LLC. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.services': 'Servicios',
    'nav.testimonials': 'Testimonios',
    'nav.faqs': 'Preguntas Frecuentes',
    'nav.contact': 'Contacto',
    'nav.book': 'Reservar Cita',
    
    // Hero Section
    'hero.badge': 'Servicios Profesionales de Confianza',
    'hero.title': 'Servicios',
    'hero.title.highlight': 'Notariales Profesionales',
    'hero.title.end': 'en los que Puedes Confiar',
    'hero.description': 'Desde notario móvil y firmas de préstamos hasta notarización remota en línea y preparación de impuestos, brindamos servicios profesionales integrales con integridad y conveniencia.',
    'hero.feature1': 'Notario Licenciado y Asegurado',
    'hero.feature2': 'Servicios Móviles Disponibles',
    'hero.feature3': 'Notarización Remota en Línea',
    'hero.feature4': 'Citas el Mismo Día',
    'hero.cta.book': 'Reserva tu Cita',
    'hero.cta.phone': '(908) 514-8180',
    'hero.stats.documents': 'Documentos Notarizados',
    'hero.stats.loans': 'Firmas de Préstamos',
    'hero.stats.satisfaction': 'Satisfacción del Cliente',
    'hero.image_alt': 'Servicios notariales profesionales - documentos oficiales y sellos',
    'hero.badge.licensed': 'Licenciado y con Garantía',
    'hero.badge.licensed_desc': 'Servicio Profesional',
    'hero.badge.ron': 'Certificado RON',
    'hero.badge.ron_desc': 'Notarización Remota',
    
    // About Section - Mission and Why Choose Us
    'about.mission.title': 'Nuestra Misión',
    'about.mission.description': 'Proporcionar servicios notariales confiables, profesionales y convenientes mientras mantenemos los más altos estándares de integridad y confidencialidad. Nos esforzamos por hacer que la notarización de documentos sea accesible y libre de estrés para cada cliente.',
    'about.cta': 'Ver Nuestras Credenciales',
    'about.why_choose.title': '¿Por Qué Elegir Notary and Signings LLC?',
    'about.why_choose.subtitle': 'Nuestra dedicación a la excelencia profesional y la satisfacción del cliente nos distingue.',
    'about.why_choose.excellence.title': 'Excelencia Profesional',
    'about.why_choose.excellence.description': 'Licenciados, con garantía y asegurados con educación y entrenamiento continuo',
    'about.why_choose.convenience.title': 'Servicio Conveniente',
    'about.why_choose.convenience.description': 'Servicios móviles, horarios flexibles y opciones de notarización remota',
    'about.why_choose.trust.title': 'Asociación de Confianza',
    'about.why_choose.trust.description': 'Servicio confidencial y confiable con enfoque en construir relaciones a largo plazo',
    'about.verify_credentials': 'Verificar Credenciales de Notario',
    'about.verify_signing_agent': 'Verificar Credenciales de Agente de Firma',
    
    // Services Section
    'services.badge': 'Nuestros Servicios',
    'services.title': 'Soluciones Notariales Integrales',
    'services.subtitle': 'Servicios profesionales diseñados para satisfacer sus necesidades de autenticación y firma de documentos.',
    'services.mobile.title': 'Notario Móvil',
    'services.mobile.description': 'Servicios notariales convenientes en el sitio en su ubicación.',
    'services.mobile.feature1': 'Viajamos a su ubicación',
    'services.mobile.feature2': 'Horarios flexibles',
    'services.mobile.feature3': 'Servicio profesional',
    'services.mobile.feature4': 'Licenciado y con garantía',
    'services.mobile.price': 'Desde $25',
    'services.loan.title': 'Firmas de Préstamos',
    'services.loan.description': 'Especializado en firmas de documentos de préstamos inmobiliarios.',
    'services.loan.feature1': 'Experiencia en bienes raíces',
    'services.loan.feature2': 'Firmas sin errores',
    'services.loan.feature3': 'Servicio el mismo día',
    'services.loan.feature4': 'Aprobado por compañías de títulos',
    'services.loan.price': 'Desde $100',
    'services.ron.title': 'Notarización Remota en Línea',
    'services.ron.description': 'Notarización segura en línea desde cualquier lugar.',
    'services.ron.feature1': 'Plataforma de video segura',
    'services.ron.feature2': 'Firma digital de documentos',
    'services.ron.feature3': 'Verificación de identidad',
    'services.ron.feature4': 'Legalmente conforme',
    'services.ron.price': 'Desde $35',
    'services.apostille.title': 'Servicios de Apostilla',
    'services.apostille.description': 'Autenticación de documentos para uso internacional.',
    'services.apostille.feature1': 'Autenticación internacional',
    'services.apostille.feature2': 'Preparación de documentos',
    'services.apostille.feature3': 'Procesamiento rápido',
    'services.apostille.feature4': 'Manejo seguro',
    'services.apostille.price': 'Desde $50',
    'services.fingerprint.title': 'Servicios de Huellas Dactilares',
    'services.fingerprint.description': 'Huellas dactilares profesionales para verificaciones de antecedentes y licencias.',
    'services.fingerprint.feature1': 'Escáner en Vivo',
    'services.fingerprint.feature2': 'Tarjetas de Tinta',
    'services.fingerprint.feature3': 'Verificación de Antecedentes',
    'services.fingerprint.feature4': 'Solicitudes de Licencia',
    'services.fingerprint.price': 'Desde $20',
    'services.tax.individual.title': 'Preparación de Impuestos (Individual)',
    'services.tax.individual.description': 'Servicios profesionales de preparación de impuestos individuales.',
    'services.tax.individual.feature1': 'Declaraciones Individuales',
    'services.tax.individual.feature2': 'Optimización de Deducciones',
    'services.tax.individual.feature3': 'Presentación Electrónica',
    'services.tax.individual.feature4': 'Planificación Fiscal',
    'services.tax.business.title': 'Declaración de Impuestos para Pequeñas Empresas',
    'services.tax.business.description': 'Servicios fiscales integrales para pequeñas empresas.',
    'services.tax.corporate.title': 'Impuestos de Sociedades y Corporaciones',
    'services.tax.corporate.description': 'Preparación avanzada de impuestos para sociedades y corporaciones.',
    'services.tax.review.title': 'Revisión y/o Enmienda de Impuestos',
    'services.tax.review.description': 'Revisión profesional y enmienda de declaraciones de impuestos existentes.',
    'services.tax.additional.title': 'Servicios Fiscales Adicionales',
    'services.tax.additional.subtitle': 'Servicios especializados de preparación de impuestos para empresas y declaraciones complejas.',
    'services.book_now': 'Reservar Ahora',
    'services.learn': 'Más Información',
    'services.popular': 'Más Popular',
    'services.areas.title': 'Áreas de Servicio',
    'services.areas.description': 'Servimos con orgullo las siguientes áreas con servicios móviles disponibles:',
    'services.areas.scotch_plains': 'Scotch Plains',
    'services.areas.perth_amboy': 'Perth Amboy',
    'services.areas.new_brunswick': 'New Brunswick',
    'services.areas.piscataway': 'Piscataway',
    'services.areas.plainfield': 'Plainfield',
    'services.areas.south_amboy': 'South Amboy',
    'services.areas.availability': 'Servicio Móvil Disponible',
    'services.areas.same_day': 'Citas el Mismo Día',
    
    // About Section
    'about.badge': 'Acerca de Nosotros',
    'about.title': 'Profesional Licenciado en Quien Puedes Confiar',
    'about.description': 'Con años de experiencia en servicios notariales y autenticación de documentos, brindamos servicios confiables y profesionales con los más altos estándares de integridad y confidencialidad.',
    'about.certification.title': 'Certificaciones Profesionales',
    'about.certification.description': 'Licenciado, con garantía y asegurado con todas las certificaciones estatales requeridas para su tranquilidad.',
    'about.experience.title': 'Años de Experiencia',
    'about.experience.description': 'Amplia experiencia en todo tipo de actos notariales y servicios de autenticación de documentos.',
    'about.mobile.title': 'Servicio Móvil',
    'about.mobile.description': 'Servicios convenientes en el sitio en su hogar, oficina o cualquier ubicación de su elección.',
    'about.stats.certifications': 'Certificaciones Profesionales',
    'about.stats.experience': 'Años de Experiencia',
    'about.stats.documents': 'Documentos Procesados',
    'about.stats.satisfaction': 'Índice de Satisfacción',
    
    // Testimonials Section
    'testimonials.badge': 'Testimonios de Clientes',
    'testimonials.title': 'Lo que Dicen Nuestros Clientes',
    'testimonials.subtitle': 'Experiencias reales de clientes satisfechos que confían en nuestros servicios notariales profesionales.',
    'testimonials.stats.professional': 'Servicio Profesional',
    'testimonials.stats.satisfaction': 'Satisfacción del Cliente',
    'testimonials.stats.clients': 'Clientes Felices',
    'testimonials.stats.rating': 'Calificación Promedio',
    'testimonials.cta.title': '¿Listo para Experimentar el Servicio Profesional?',
    'testimonials.cta.description': 'Únete a cientos de clientes satisfechos que confían en nosotros con sus documentos importantes.',
    
    // Individual Testimonials
    'testimonials.client1.name': 'Sarah Johnson',
    'testimonials.client1.role': 'Agente de Bienes Raíces',
    'testimonials.client1.content': 'Notary and Signings LLC ha sido nuestra opción principal para todas las firmas de préstamos. Su profesionalismo y atención al detalle es excepcional. Hacen que el proceso de cierre sea fluido para nuestros clientes.',
    'testimonials.client1.service': 'Firma de Préstamo',
    
    'testimonials.client2.name': 'Michael Chen',
    'testimonials.client2.role': 'Propietario de Pequeña Empresa',
    'testimonials.client2.content': 'El servicio de notario móvil me ahorró mucho tiempo. Vinieron a mi oficina en 2 horas y manejaron todos mis documentos comerciales profesionalmente. ¡Muy recomendado!',
    'testimonials.client2.service': 'Notario Móvil',
    
    'testimonials.client3.name': 'Lisa Rodriguez',
    'testimonials.client3.role': 'Profesional Trabajadora',
    'testimonials.client3.content': 'La notarización remota en línea fue perfecta para mi situación. La videollamada fue segura y profesional, y recibí mis documentos notarizados inmediatamente. ¡Excelente servicio!',
    'testimonials.client3.service': 'Servicio RON',
    
    'testimonials.client4.name': 'David Thompson',
    'testimonials.client4.role': 'Jubilado',
    'testimonials.client4.content': 'Necesitaba mi declaración de impuestos preparada y documentos notarizados. Manejaron todo con cuidado y explicaron cada paso. Servicio confiable y de confianza.',
    'testimonials.client4.service': 'Preparación de Impuestos',
    
    'testimonials.client5.name': 'Jennifer Park',
    'testimonials.client5.role': 'Trabajadora de la Salud',
    'testimonials.client5.content': 'Servicio rápido de huellas dactilares para la renovación de mi licencia. Configuración profesional y respuesta rápida. Hicieron que el proceso fuera fácil y sin estrés.',
    'testimonials.client5.service': 'Huellas Dactilares',
    
    'testimonials.client6.name': 'Robert Williams',
    'testimonials.client6.role': 'Estudiante Internacional',
    'testimonials.client6.content': 'Necesitaba servicios de apostilla para mis documentos para usar en el extranjero. Manejaron todo el proceso y me mantuvieron informado durante todo el proceso. ¡Excelente servicio!',
    'testimonials.client6.service': 'Apostilla',
    
    // FAQ Page
    'faqs.badge': 'Preguntas Frecuentes',
    'faqs.title': '¿Cómo Podemos Ayudarte?',
    'faqs.subtitle': 'Encuentra respuestas a las preguntas más comunes sobre nuestros servicios notariales, precios y procesos.',
    'faqs.contact.title': '¿Aún Tienes Preguntas?',
    'faqs.contact.description': 'Si no puedes encontrar la respuesta que buscas, no dudes en contactarnos directamente. ¡Estamos aquí para ayudar!',
    
    // FAQ Categories
    'faqs.general.title': 'Preguntas Generales',
    'faqs.general.q1.question': '¿Qué es un notario público y qué hace?',
    'faqs.general.q1.answer': 'Un notario público es un funcionario nombrado por el estado que sirve como testigo imparcial de la firma de documentos importantes. Verificamos la identidad de los firmantes, nos aseguramos de que entiendan lo que están firmando y confirmamos que firmen voluntariamente sin coerción.',
    'faqs.general.q2.question': '¿Qué documentos necesito traer para la notarización?',
    'faqs.general.q2.answer': 'Necesitarás:\n• Una identificación con foto válida emitida por el gobierno (licencia de conducir, pasaporte o identificación estatal)\n• El/los documento(s) sin firmar para notarizar\n• Cualquier documentación adicional especificada por los requisitos del documento',
    'faqs.general.q3.question': '¿Están licenciados y asegurados?',
    'faqs.general.q3.answer': 'Sí, somos notarios públicos completamente licenciados en el estado de Nueva Jersey, con garantía y portamos $100,000 en seguro de responsabilidad profesional para su protección y tranquilidad.',
    'faqs.general.q4.question': '¿Cuáles son sus horarios comerciales?',
    'faqs.general.q4.answer': 'Operamos de lunes a domingo, de 8AM a 8PM, solo con cita previa. Ofrecemos horarios flexibles para acomodar su agenda ocupada, incluyendo citas nocturnas y de fin de semana.',
    
    'faqs.mobile.title': 'Servicios de Notario Móvil',
    'faqs.mobile.q1.question': '¿Viajan a mi ubicación?',
    'faqs.mobile.q1.answer': '¡Sí! Proporcionamos servicios de notario móvil dentro de 25 millas de Edison, NJ. Iremos a su hogar, oficina, hospital o cualquier ubicación conveniente por una tarifa de viaje adicional.',
    'faqs.mobile.q2.question': '¿Cuánto cuesta el servicio móvil?',
    'faqs.mobile.q2.answer': 'El servicio de notario móvil es $75 por 1 hora, que incluye tiempo de viaje y notarización de sus documentos. El tiempo adicional se factura en incrementos de 15 minutos.',
    'faqs.mobile.q3.question': '¿Qué tan rápido pueden venir a verme?',
    'faqs.mobile.q3.answer': 'Típicamente podemos programar citas el mismo día con 2-4 horas de aviso. Para solicitudes urgentes, por favor llámenos directamente al (908) 514-8180.',
    
    'faqs.ron.title': 'Notarización Remota en Línea (RON)',
    'faqs.ron.q1.question': '¿Qué es la Notarización Remota en Línea?',
    'faqs.ron.q1.answer': 'RON le permite obtener documentos notarizados en línea a través de una videoconferencia segura. Puede estar en cualquier lugar del mundo mientras verificamos su identidad digitalmente y presenciamos su firma electrónica.',
    'faqs.ron.q2.question': '¿Qué necesito para RON?',
    'faqs.ron.q2.answer': 'Necesitará:\n• Una computadora, tableta o teléfono inteligente con cámara y micrófono\n• Conexión estable a internet\n• Identificación con foto válida emitida por el gobierno\n• El documento en formato PDF (podemos ayudar a convertir si es necesario)',
    'faqs.ron.q3.question': '¿Es RON legalmente válido?',
    'faqs.ron.q3.answer': 'Sí, RON es legalmente válido y reconocido en Nueva Jersey y muchos otros estados. El documento notarizado electrónicamente tiene el mismo peso legal que una notarización tradicional en papel.',
    
    'faqs.loan.title': 'Servicios de Firma de Préstamos',
    'faqs.loan.q1.question': '¿Qué es un agente de firma de préstamos?',
    'faqs.loan.q1.answer': 'Un agente de firma de préstamos es un notario especialmente entrenado que maneja la firma de documentos de préstamos inmobiliarios. Nos aseguramos de que todos los documentos se firmen correctamente y se devuelvan a la compañía de títulos o prestamista prontamente.',
    'faqs.loan.q2.question': '¿Cuánto tiempo toma una firma de préstamo?',
    'faqs.loan.q2.answer': 'La mayoría de las firmas de préstamos toman 1 hora para completarse. Permitimos tiempo suficiente para revisar documentos, responder preguntas y asegurar que todo se firme correctamente.',
    'faqs.loan.q3.question': '¿Trabajan con todas las compañías de títulos y prestamistas?',
    'faqs.loan.q3.answer': 'Sí, trabajamos con compañías de títulos, prestamistas y servicios de firma en todo Nueva Jersey. Estamos aprobados por las principales compañías de títulos y mantenemos los más altos estándares de profesionalismo.',
    
    'faqs.pricing.title': 'Precios y Pago',
    'faqs.pricing.q1.question': '¿Qué formas de pago aceptan?',
    'faqs.pricing.q1.answer': 'Aceptamos efectivo, cheque, Venmo, Zelle y todas las principales tarjetas de crédito. El pago vence al momento del servicio.',
    'faqs.pricing.q2.question': '¿Hay tarifas adicionales?',
    'faqs.pricing.q2.answer': 'Nuestros precios son transparentes. El servicio móvil incluye viaje dentro de 25 millas. Para ubicaciones más allá de 25 millas, hay una tarifa adicional por milla. El servicio urgente (menos de 2 horas de aviso) puede incluir una tarifa adicional.',
    'faqs.pricing.q3.question': '¿Ofrecen descuentos para múltiples documentos?',
    'faqs.pricing.q3.answer': 'Sí, ofrecemos precios competitivos para múltiples documentos durante la misma cita. Contáctenos para una cotización personalizada para paquetes grandes de documentos.',
    
    // Contact Section
    'contact.badge': 'Contáctanos',
    'contact.title': '¿Listo para Comenzar?',
    'contact.subtitle': 'Contáctanos hoy para programar tu cita notarial u obtener respuestas a tus preguntas.',
    'contact.info.location': 'Nuestra Ubicación',
    'contact.info.location.address': '180 Talmadge Road, Unit 1380, Edison, NJ 08817',
    'contact.info.phone': 'Número de Teléfono',
    'contact.info.email': 'Dirección de Correo',
    'contact.info.hours': 'Horario Comercial',
    'contact.info.hours.schedule': 'Lun-Dom: 8AM-8PM',
    'contact.info.hours.description': 'Disponibilidad de lunes a domingo',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.service': 'Servicio Necesario',
    'contact.form.service.mobile': 'Notario Móvil',
    'contact.form.service.loan': 'Firma de Préstamo',
    'contact.form.service.ron': 'Notarización Remota',
    'contact.form.service.apostille': 'Servicio de Apostilla',
    'contact.form.service.other': 'Otros Servicios',
    'contact.form.timing': 'Horario Preferido',
    'contact.form.timing.morning': 'Mañana (8AM-12PM)',
    'contact.form.timing.afternoon': 'Tarde (12PM-5PM)',
    'contact.form.timing.evening': 'Noche (5PM-8PM)',
    'contact.form.timing.flexible': 'Horario Flexible',
    'contact.form.message': 'Mensaje',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.response': 'Responderemos dentro de 2 horas durante el horario comercial.',
    'contact.hours.monday': 'Lunes - Viernes',
    'contact.hours.saturday': 'Sábado',
    'contact.hours.sunday': 'Domingo',
    'contact.hours.appointment': 'Solo con cita previa',
    'contact.hours.appointment_only': 'Solo con Cita Previa',
    'contact.emergency.title': 'Servicios Profesionales',
    'contact.emergency.description': 'Servicios notariales licenciados, con garantía y asegurados con programación flexible para satisfacer sus necesidades.',
    
    // Footer
    'footer.company': 'Notary & Signings LLC',
    'footer.description': 'Servicios notariales profesionales en los que puedes confiar. Licenciado, con garantía y asegurado para tu tranquilidad. Sirviendo a la comunidad con integridad y excelencia.',
    'footer.quick_links': 'Enlaces Rápidos',
    'footer.services': 'Nuestros Servicios',
    'footer.credentials': 'Credenciales Profesionales',
    'footer.licensed': 'Notario Licenciado',
    'footer.licensed_desc': 'Certificado por el Estado',
    'footer.bonded': 'Con Garantía y Asegurado',
    'footer.bonded_desc': 'Cobertura de $100K',
    'footer.ron_certified': 'Certificado RON',
    'footer.ron_desc': 'Notarización Remota',
    'footer.verify_notary': 'Verificar Credenciales de Notario',
    'footer.verify_signing': 'Verificar Credenciales de Agente de Firma',
    'footer.professional_services': 'Servicios Profesionales',
    'footer.professional_desc': 'Servicios notariales licenciados, con garantía y asegurados con programación flexible.',
    'footer.schedule': 'Programar Cita',
    'footer.copyright': '© 2024 Notary and Signings LLC. Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.cookies': 'Política de Cookies',
  }
};